### ISSUE TITLE
return statement in a running nursery doesn't stop the function

### ISSUE THREAD

**Issue by math2001** [python-trio/trio#1009]
Firstly, thank you so much for trio, it's absolutely awesome ❤️ 

A return statement in a nursery doesn't exit the function straight away, it still waits for the nursery to be done. So for example:

```python
async def main():
    async with trio.open_nursery() as nursery:
        nursery.start_soon(trio.sleep, 5)
        await trio.sleep(1)
        print("returning")
        return # expected to cancel the nursery, but doesn't

    print("I'm never printed") # that's normal
```

This code would exit after 5 seconds, not 1 second. To make it stop at 1 second, we have to cancel it manually (which I thought was going to be done by trio):

```python
return nursery.cancel_scope.cancel()
```

So, I'm not sure if this is known, or if it should be changed, or if I'm missing something but I think it should be part of the documentation somewhere in the [nursery section](https://trio.readthedocs.io/en/latest/reference-core.html#tasks-let-you-do-multiple-things-at-once).

**Comment by njsmith** [comment]
Yeah, that's working correctly (though maybe not intuitively!). The nursery is only cancelled if (a) there's an exception, or (b) if you use `nursery.cancel_scope` to cancel it explicitly.

We don't really have a choice in the matter, because the way Python works, there's no way for Trio to tell the difference between:

```python
async with trio.open_nursery() as nursery:
    nursery.start_soon(...)
    return
```

and 

```python
async with trio.open_nursery() as nursery:
    nursery.start_soon(...)
return
```

So I guess the question is how to make this clearer in the docs...
