### ISSUE TITLE
Usecase for nested run

### ISSUE THREAD

**Issue by namedLambda** [python-trio/trio#1080]
I have a package that's written to take strings or a lists of strs. In the case of list[str], I use trio to batch send the requests using the contents of the list and then return, for this I am using `trio.run`. I would like, if possible to keep the function call synchronous and simply block the call thread until it's finished.

I am attempting to write a script to go through a series of files and process them. The processing part happens interactively with the server and a file can only be processed sequentially.

My only method of saturating the network is to process the files in parallel, which brings me to the issue of nested `trio.run`.

**Comment by njsmith** [comment]
So:

* You have a lowest-level function, call it `function1`, that takes a list of strings, and internally it uses `trio.run` to start up a bunch of tasks and process all the strings in parallel.
* You have a second-level function, call it `function2`, that does a call to `function1`
* And then you want to use trio to run lots of calls to `function2` in parallel

Is that right?

**Comment by namedLambda** [comment]
Yes that's it. `function1` is in a different package that is used by other people so I'd rather not introduce any changes to that.

**Comment by njsmith** [comment]
So unfortunately nested run would not help with your problem :-(

We could make it so that it was allowed to call `trio.run` inside an existing call to `trio.run`. Then you could use a first `trio.run` to make lots of calls to `function2` in parallel, and inside each call it would eventually use `trio.run` to do a bunch of requests in parallel.

But, each time you make an inner call to `trio.run`, it blocks the thread until it finishes. Which means... the outer `trio.run` can't switch between tasks. It's stuck executing only one call to `function2` at a time. This is a fundamental limitation of how Python's async/await syntax works, and I think it makes nested run useless for you.

Generally the best solution in a situation like this is to do something like:

```python
async def function1_async(...):
    async with trio.open_nursery() as nursery:
        ...

# Backwards-compatible, synchronous/blocking version:
def function1(...):
    return trio.run(function1_async, ...)
```

So now your users who like the old `function1` can keep using it, no problem, but they also have the choice of the `function1_async` if they want.

And then in your `function2`, you can use `function1_async`, and run everything in a single call to `trio.run`.

If this isn't possible, the other hack would be to do what you're already doing, but instead of calling `function2(...) directly, do `await trio.run_sync_in_worker_thread(function2, ...)`. Trio does let you make multiple calls to `trio.run` at the same time as long as each one happens in its own thread. The downside of this is that it's impossible to cancel a thread (another Python limitation), so control-C won't work.

**Comment by namedLambda** [comment]
Ah I see, thanks a lot for the help and the great project. I expected creating an async version would have been the solution. Thanks a lot!

**Comment by njsmith** [comment]
Good luck!
