### ISSUE TITLE
Add CI for FreeBSD (and other BSDs?)

### ISSUE THREAD

**Issue by thedrow** [python-trio/trio#1118]
See https://cirrus-ci.org/guide/FreeBSD/ for details.

**Comment by njsmith** [comment]
Sounds fine to me.

**Comment by njsmith** [comment]
For the record: I "installed" the Cirrus-CI app on the python-trio org, at @thedrow's request. So I think this just needs someone to put together a PR with a `.cirrus.yml` in it.

Our general strategy for these CI systems is to try to keep the logic in the `.yml` file to the bare minimum, and do everything else through `ci.sh` (which is shared across CI platforms).

**Comment by njsmith** [comment]
There's some more discussion of Cirrus here: https://github.com/python-trio/trio/pull/1128

Summary:

- The trio tests have some problems on freebsd, so that needs to be sorted out before we could enable CI testing
- Cirrus works, but is slow and we ran into some bugs even on just this first test PR, which isn't very confidence inspiring.

It's possible that Cirrus has gotten better since then, or will by the time anyone gets around to fixing the tests.

There are also some other options for BSD testing though:

- We can use nested virtualization on Travis to run tests on arbitrary OSes. Currently we're using this to test our support for cutting edge Linux kernel APIs, but it would work for BSDs too.

  This is also kind of slow. It might or might not be faster than Cirrus; we'd have to check. It's definitely a bit complicated to set up.

- We could use SourceHut's "builds" feature, which has full support for BSDs and GitHub: https://sourcehut.org/blog/2019-09-12-sourcehut-makes-bsd-software-better/ (thanks to @wgwz for bringing this to my attention)

  Unlike the other options here, this is technically a paid service. It's a tiny self-funded operation, so they ask that somebody pay something like $50-100/year to use it: https://sourcehut.org/pricing/ They're really not making any money off it, and we could test it out for free before committing.

Anyway, if someone wants to push this forward, the first step is just to get the tests passing.

**Comment by njsmith** [comment]
NB: github actions currently also supports nested virtualization *but* only on their macOS runners.
