### ISSUE TITLE
Is __aexit__ magic the best approach?

### ISSUE THREAD

**Issue by merrellb** [python-trio/trio#137]
I do like the elegance of the current nursery ```__aexit__``` magic but wonder if something more explicit would be more pythonic.   My thought was to require awaiting the nursery at the end of the scope (eg ```await nursery.done()```, ```await nursery.run()```, etc) and ```__aexit__``` could just raise an exception if the nursery wasn't closed.  This would also have the advantage of providing something to wrap, allowing users to catch exceptions within the nursery scope (and presumably continue)

**Comment by njsmith** [comment]
Technically it certainly would be possible to have a method that does the same thing as `__aexit__`. I hesitate a little though.

The cleanup code has to be called on both regular exit and if the code directly inside the nursery block raises an exception. (E.g. `spawn` can fail in various circumstances.) So if we were really going to make this explicit, it would look like:

```python
async with open_nursery() as nursery:
    try:
        ...
    finally:
        await nursery.supervise()
```

... Except no, wait, that's totally broken, because it has to act differently if the `finally` block gets entered by an exception or normally. So I guess it should be

```python
async with open_nursery() as nursery:
    try:
        ...
    except BaseException as exc:
        await nursery.supervise(exc)
    finally:
        await nursery.supervise()
```

... But now we've just reinvented the `with` block?

Or of course it would *work* to write something like
```python
async with open_nursery() as nursery:
    ...
    await nursery.supervise()
```
Because either we hit the `supervise` call, or else an exception is raised and we hit `__aexit__` and they do exactly the same thing? But this seems a bit misleading...

I dunno, though, maybe this will be a persistent confusion for everyone and we'll have to do something; I hope not but it's hard to predict...

> This would also have the advantage of providing something to wrap, allowing users to catch exceptions within the nursery scope (and presumably continue)

The way the nursery cleanup/supervision code responds to an exception is to cancel the nursery scope and all its children; it never returns without making sure all children are dead and that no new children can be spawned into this nursery. So catching the cleanup function's exception inside the nursery scope is not very useful – probably what you want instead is to wrap the entire nursery block in a `try`, or to catch exceptions inside the individual children (like in the tutorial echo server), or to make a custom supervisor that implements some fancy logic like tracking when a child dies and respawning it.

**Comment by merrellb** [comment]
I think the last option is the closest to what I was thinking and but perhaps with divided functionality. 

```__aexit__``` would handle abnormal termination (errors directly in the block and uncaught nursery exceptions) while assuring all tasks are canceled when leaving.

 ```supervise()``` would handle the normal nursery functionality (blocking until task completion, reaping, etc).

While I can see the need to cancel all tasks as we leave the scope in ```__aexit___```, I could foresee wanting to catch exceptions without automatically canceling in ```supervise```. In a server scenario, we would have built up a lot of state in our tasks that would be a pain to recreate (even if we can catch the cancellations and persist).  It would be slick to be able to catch an exception, deal with it and then call supervise again without having to exit the nursery and recreate all of our tasks.

I am new to this style of programming (and really enjoying it :-) but my naive understanding of "with" is that ```__aexit__``` is more for cleaning up than blocking indefinitely to do work.  It sometimes feels a bit misleading to have so much processing going on in a statement that can't actually be viewed in my code (part of why tracebacks on the seemingly unrelated last lines in the scope were confusing me early on).

**Comment by oremanj** [comment]
I think that given "simplified nurseries" this is no longer relevant. I guess we could make leaving the `async with` block cancel all tasks, and require people to write `await nursery.join()` if they want to not cancel. But that seems like rather too dramatic of an API change to contemplate at this stage...
