### ISSUE TITLE
Controlling backpressure through SO_RCVBUF and SO_SNDBUF on MacOS/OSX

### ISSUE THREAD

**Issue by merrellb** [python-trio/trio#146]
I am sending numerous small Websocket messages and would like to keep latency low. However, I've noticed that my MacOS system, ~550KB can be sent before ```sendall``` blocks (intentionally receiving data slowly on the far end).  I've tried what I thought were the correct options but with little impact (buffering seems to decrease slightly).
```
mysocket.setsockopt(trio.socket.SOL_SOCKET, trio.socket.SO_RCVBUF, 1024)
mysocket.setsockopt(trio.socket.SOL_SOCKET, trio.socket.SO_SNDBUF, 1024)
```
I've applied these options quite liberally (before and after connect() and bind()) and have verified the settings with ```getsockopt```.  Is there another mechanism I am missing that impacts buffering?

**Comment by njsmith** [comment]
To check first... are you setting these on both the server and the client?

In theory there are better alternatives to setting those to be really tiny, like better traffic shaping and `TCP_NOTSENT_LOWAT`, but we can fiddle with that after you've figured out why the simple/crude thing isn't working...

(Trio should actually be enabling `TCP_NOTSENT_LOWAT`, but it has weird semantics on MacOS that mean it won't actually help you much by default – it only kicks in when someone explicitly asks if the socket is writable, not if you go ahead and try writing to it. So making this work seamlessly is a bit of a todo item still :-).)

**Comment by merrellb** [comment]
Yep, I've set these options on the client and server.

**Comment by njsmith** [comment]
Huh, this is odd. Playing around with this on a local MacOS machine in the REPL, it looks like MacOS resets the receive buffer to whatever size it thinks it "should" be, whenever new data arrives. That's kind of annoying...

I tried:

1) Opening a listening socket in one terminal:
```python
# terminal A
import socket
listen_sock = socket.socket()
listen_sock.bind(("127.0.0.1", 12345))
listen_sock.listen(1)
server_sock, _ = listen_sock.accept()
```
2) connecting from a second terminal
```python
# terminal B
import socket
client_sock = socket.socket()
client_sock.connect(("127.0.0.1", 12345))
```

3) set the server socket to a small receive buffer
```python
# terminal A
server_sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 1024)
# Prints "1024":
print(server_sock.getsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF))
```

4) send some data from the client to the server
```python
# terminal B
client_sock.send(b"foo")
```

5) Check the server... the receive buffer grew:
```python
# prints "262336"
print(server_sock.getsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF))
```

This certainly seems to explain what you're seeing though I'm not sure what to tell you...

**Comment by merrellb** [comment]
Yeah, I can confirm that as well.  Strangely a few quick searches do not seem to turn up much on this issue (could it be Python specific?).  Given how trio (and curio) are focused on correct backpressure, it is frustrating to have ~20k of small message latency before getting any pressure!

You mentioned traffic shaping and ```TCP_NOTSENT_LOWAT```.  Anything I should try on those fronts?

**Comment by merrellb** [comment]
I figured out how to disable the autotuning on MacOS/OSX:
sudo sysctl -w net.inet.tcp.doautosndbuf=0
sudo sysctl -w net.inet.tcp.doautorcvbuf=0

The fact I need to dig into sysctl makes me wonder if I am approaching this wrong? :-)

**Comment by njsmith** [comment]
I *really* doubt it's Python specific; the Python socket module is a pretty thin wrapper.

Do keep in mind that localhost networking is Often Weird – this may or may not happen or cause a problem on real networks. And unless you're actually planning to have clients receive slowly for some reason, that part may not be representative either – in theory the OS is trying to adapt the receive buffer to match the characteristics of the network, which here is very fast, not the application. And eventually we'll have stuff like BBR that makes TCP do the right thing even if the buffers are the wrong size.

But yeah for now there's a limit to what you can accomplish purely through TCP backpressure... It's getting better but...

Traffic shaping isn't really something that works on localhost; it's about making sure you don't send packets faster than your known outgoing bandwidth. `TCP_NOTSENT_LOWAT` is also about throttling outgoing data; it can't help if the receive side has decided to buffer up a bunch of data.

I agree that sysctl is probably the wrong solution :-). Is this causing an measurable end-to-end problem?

Another general strategy (hack) is to do your own simple flow control, like: "every time the client receives a message, it sends back a message saying 'thanks, got it', and the server waits until it sees that before sending the next message". As written this will kill your throughput, but it sounds like for this application you might not care, and the resulting latency is within a factor of two of optimal.

**Comment by merrellb** [comment]
I am currently just experimenting and trying to grok trio and async, mainly in the context of Websockets.  I first noticed this issue when my Websocket "close" message was getting backed up behind thousands of regular messages in the send/receive buffers.  I simultaneously wasn't sure what had been processed on the far-end and how long I needed to sleep (or await an application level ack) before closing the connection.

Although in this case I artificially slowed the server when testing, I think it is fairly realistic to imagine a server not being able to keep up with a firehose of messages from multiple connected clients. While buffers can be helpful for bursts, it would be nice to have the option of pushing backpressure quickly (eg queue sizes of 1) to reduce message generation.  In my ideal world, networking could act similarly with, ```sendall``` blocking until  ```recv``` (or multiple calls to it) had read the entire single message on the far end.  Is there any way to do this without waiting for an application level per-message ack?

I liked your Curio paper and particularly the issues you raised about how other approaches with background writers run into memory and latency issues with slow clients of proxies or Websockets.  However, large and dynamic buffers seem almost as bad, with ```sendall()``` often acting synchronously while background (but OS) magic delivers the data?  I realize that being bounded is a critical difference but the fact that latency and buffer memory per connection can vary widely seems to keep many of the challenges.

**Comment by njsmith** [comment]
>  In my ideal world, networking could act similarly with, sendall blocking until recv (or multiple calls to it) had read the entire single message on the far end. Is there any way to do this without waiting for an application level per-message ack?

No, if these are the semantics you want then a per-message ack is exactly the way to implement it. TCP doesn't provide this information otherwise; the only information the sender gets is a notification of when the data has entered the remote side's kernel receive buffer, not when it's been read out.

Note also that the policy you has a really extreme bias towards latency over throughput. That may well make sense for your application, but TCP doesn't know that :-). Like, imagine if file downloads worked like this: you'd send 1 packet, then you'd wait for an acknowledgement, then you'd send the next packet, etc. It's entirely realistic for big international fiber connections to be able to push 1 gigabyte per second, with 100 ms+ transmission latency. With your model, on a pipe like that, you get to send 1 packet every 200 ms. That's like less than 10 kilobytes per second. If you want to do better than that, then you *have* to be willing to speculatively push more data into the pipe and hope that everything works out. But then if you push too much, your latency dies.

The challenge for folks working on stuff like TCP and routers and etc. is to design algorithms so that they can get good throughput *and* good latency at the same time. And to do it in this horribly messy system where every router in between you and the other side has its own buffers, and then there's the TCP control loop on top, and etc. etc. And there's actually been massive massive progress on this in the last few years, but it requires changes all through the system. Curio/Trio's approach is one part of that, and a critical part, but unfortunately we can't magically fix all the networking equipment in the world :-(.

**Comment by merrellb** [comment]
Thank you for the additional thoughts/explanation.  Does ```sendall``` block until all "the data has entered the remote side's kernel receive buffer?"  If so that actually sounds pretty good as the only "hidden" latency is something we can control (assuming SO_RCVBUF works :-)

**Comment by njsmith** [comment]
@merrellb: no, `sendall` blocks until all the data has entered the local side's send buffer. But there is a relationship between those things: by default, the local send buffer holds onto each piece of data until it gets notified that it's entered the remote side's receive buffer (because it might have to re-send it). So if the local send buffer becomes full, then `sendall` blocks until *some* data has entered the remote side's receive buffer (and the notification has made it back to the local side).

It turns out that this is not really what you want, though; really you want to put data into the send buffer based on how much *unsent* data there is locally, not how much unacknowledged data there is. That's what TCP_NOTSENT_LOWAT does. There's a discussion here: https://github.com/dabeaz/curio/issues/83

(Also all the above is ignoring the effects of the TCP window, which also limits how fast data can be sent. I'm not sure where exactly it affects things.)

This is a really complicated topic, because what we have is really a whole chain of individual buffers and control loops all coupled together, and then there's the TCP control loop on top of it. If you're interested in understanding more, there's a whole deep literature on this stuff; some starting points might be

https://en.wikipedia.org/wiki/TCP_tuning
https://en.wikipedia.org/wiki/Bufferbloat
https://en.wikipedia.org/wiki/CoDel
https://blog.acolyer.org/2017/03/31/bbr-congestion-based-congestion-control/

The BBR talks are also useful for getting a more informal sense of how experts think about this stuff: https://groups.google.com/forum/#!topic/bbr-dev/zM2HOIaNoXE

**Comment by njsmith** [comment]
Anyway... it sounds like in your setup, you have something like a continuously monitoring sensor, and you want to send regular snapshots to a central server? and you want to optimize for metrics like, average staleness of the server's information, worst case staleness of the server's information, etc.? I think the best design here really depends a lot on the details: the approach of sending one, waiting for acknowledgement, sending another, etc. loop gives you a system where the server's staleness varies from 0.5x RTT to 1.5x RTT, with an average of 1 RTT and the upper bound being tight. If that's good enough for your application then it's hard to beat the simplicity :-).

OTOH the best you could possibly hope for is to keep the server's staleness down to 0.5x RTT (which is what you get if you send continuously, but *just* slowly enough that no messages back up), so if you need something better than that you had better find a way to change the problem. And if you really need something in between, then you might need to get clever.

I guess another very simple strategy would be to send a packet every N milliseconds on a timer; then your staleness varies between 0.5x RTT and (0.5x RTT + N milliseconds), where you choose N small enough to meet your staleness requirements while being large enough that in practice it never overwhelms your network connection. (But if the server becomes continuously overloaded, or the network overwhelmed, then it's possible that congestion would occur anyway.)

**Comment by merrellb** [comment]
I really appreciate all your thoughts on this.  I will read up on and do some experiments with application-level acknowledgments and perhaps a periodic heartbeat/message.  Since the initial MacOS specific issue has been addressed (and dealing with TCP is probably an entire FAQ :-) I will close this ticket.  Thanks again.
