### ISSUE TITLE
Idea: rename Semaphore to Sofa?

### ISSUE THREAD

**Issue by Akuli** [python-trio/trio#156]
Once a friend of mine explained me what a semaphore is really nicely. He said that it's like a sofa, at most n people can sit on it at a time and others need to wait for free seats. I would have probably never understood what semaphores are without this explanation.

Trio already has nurseries instead of task groups, so I think it would make sense to have sofas instead of semaphores.

**Comment by njsmith** [comment]
Ha, that's great!

Semaphores do have practical usage patterns that don't fall into the Sofa pattern -- for example, trio.Queue uses a Semaphore whose value starts at zero and then `put` releases and `get` acquires, so it tracks how many items are available in the Queue's buffer.

But maybe it would make sense to have Sofa be a more specialized and friendly Semaphore, that enforces that a task can't release unless it has already acquired? (`trio.Lock` already departs from `threading.Lock` in this regard... a `threading.Lock` can be released by any thread, even one that didn't acquire it. `trio.Lock` is pickier.)

**Comment by Akuli** [comment]
Sounds good to me. Sofa probably shouldn't inherit from Semaphore because it should have user-friendly method names, like `take_a_seat` instead of `acquire`.

**Comment by njsmith** [comment]
I guess a more boring but possibly also more discoverable name for such a primitive would be `CapacityLock` or similar.

**Comment by theelous3** [comment]
Who says sofa's are immutable: https://www.youtube.com/watch?v=_zfni9tetRM

**Comment by Akuli** [comment]
We could also rename Lock to Chair, but I think that would be overkill. People can't really guess what a chair would do and locks aren't hard to understand.

**Comment by njsmith** [comment]
Another argument for having a dedicated class for this is that if we enforce the rule that only the task that acquired the sofa-seat could release it, then we could use that information later to automatically detect bugs like a task that exits without giving up its seat, or even potentially do deadlock detection. (Deadlock detection relies on reasoning like: task 1 can't make progress until lock A is released, and lock A can only be released by task 2, and task 2 can't make progress until lock B is released, but lock B can only be released by task 1, therefore we have a bug. With traditional semaphores and Python's `threading.Lock`, the "lock X can only be released by task Y" steps don't work, so you can't really do deadlock detection AFAICT.)

However, I'm still not sure that `Sofa` is a better name than `CapacityLimit`. I love the `Sofa` name but I feel like there's a risk it'd create a [barrier for newcomers](https://conferences.oreilly.com/oscon/oscon-tx-2016/public/schedule/detail/49092) and if so that would have to take priority...

**Comment by Akuli** [comment]
Currently @theelous3's [asks docs](http://asks.readthedocs.io/en/latest/idioms.html#sanely-making-many-requests-with-semaphores) say that "a semaphore is like a sofa". Maybe it would be nicer to just have a Sofa to begin with? We already have nuresies :)

**Comment by njsmith** [comment]
Yeah... sadly, I think a project like this has a non-zero but very limited budget for whimsical naming, and I eventually decided we should reserve it for more central and unusual concepts like nurseries. If I'm looking for a way to limit how many things are happening at once to avoid overloading things, then maybe I won't look for `CapacityLimiter` directly but I'll probably notice it if I'm skimming through the API docs, while `Sofa` is not so discoverable.

(But you should totally feel free to `from trio import CapacityLimiter as Sofa`. *We* know what it really is.)
