### ISSUE TITLE
Memory channels and timeout

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#1626]
IMHO, conceptually, sending something to a memory channel which is not full should not take any time.

```
import trio
async def main():
    s,r = trio.open_memory_channel(3)
    with trio.fail_after(0):  # or 0.0000000001
        await s.send(123)
trio.run(tmain)
```
This code should not fail.

I'm doing this with a timeout of 0.01 in my production code. Surprise: I get an error every couple of hours, presumably because Trio runs some other task that takes too long before attempting to add the data to the channel, or maybe because the system is just slow-ish for other reasons.

**Comment by gmacon** [comment]
Would using [`send_nowait`](https://trio.readthedocs.io/en/stable/reference-core.html#trio.MemorySendChannel.send_nowait) work in your case, or have you simplified away something that makes `send_nowait` not the right answer?

**Comment by smurfix** [comment]
The latter. My "other" actual problem (i.e. the one that has a timeout of 2 instead of 0.1) requires handling a full queue gracefully. `nowait` is a large hammer that isn't able to apply back pressure to the sending side. Also, dealing with a "blocked" queue which is in fact empty, or nearly so, is the worst thing you can do when the actual problem lies elsewhere (e.g. a busy or swapping host) because tearing down the receiver, restarting it, then re-syncing the data causes even more load.

Also, I've since found that this causes compatibility problems with `anyio`, (a) because it can't wrap `nowait` calls, (b) because asyncio's queue doesn't have this problem.

**Comment by njsmith** [comment]
I can't think of any way that Trio could tell the difference between your case, versus any other case where `send` is called in a cancelled context... Trio can't tell that the reason the timeout expired is because of swapping and that the body *would* have run quickly otherwise, and once it's expired the scope gets cancelled.

So I think this reduces to: you're requesting that `send` only issue a checkpoint if the queue is full and it has to block. (Which I'm guessing is what you're seeing on asyncio.)

That's pretty easy to implement on Trio:

```python
async def send_with_optional_checkpoint(channel, obj):
    try:
        channel.send_nowait(obj)
    except trio.WouldBlock:
        await channel.send(obj)
```

I'm wary about making this the default behavior though, because (a) adding special cases like this makes Trio harder to understand, (b) I think unconditional checkpointing usually is the right default, since when you forget checkpoints that almost always manifests as flaky edge cases that are hard to predict or debug.

(I'm also kind of unclear on how `send_nowait` is actually different than what you're trying to accomplish with a timeout of 0.01?)

So at least as far as Trio's API is concerned, I feel like the current situation is about as good as it can be?

I see that you have a further issue because you're not using Trio's API directly so you can't necessarily take advantage of the features we offer to solve this problem, but I'm not quite sure what to do about that.

**Comment by smurfix** [comment]
OK, fair enough.
