### ISSUE TITLE
move_on_after inside nursery behaves surprisingly

### ISSUE THREAD

**Issue by RmStorm** [python-trio/trio#1640]
Hello, I am looking into using trio since [this blogpost](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/) really has me convinced that there are some missing puzzle pieces in async code and trio might be a solution. While I was playing around with trio I ran into this very surprising behaviour:
```python
import time
import trio


async def heartbeat():
    while True:
        start = time.time()
        await trio.sleep(1)
        delay = time.time() - start - 1
        print(f'heartbeat delay = {delay:.3f}s')


async def main():
    async with trio.open_nursery() as nursery:
        with trio.move_on_after(5):
            nursery.start_soon(heartbeat)
        await trio.sleep(2.5)
        print('Start doing a thing')


if __name__ == '__main__':
    trio.run(main)
```
This does not behave as expected and after a little but of troubleshooting the [answer was right in the docs](https://trio.readthedocs.io/en/stable/reference-core.html#child-tasks-and-cancellation)! However, the documentation doesn't negate the surprise. Is there any reasonable way to have this behave as expected? Or is this gotcha unavoidable due to architecture of trio?

Just to be clear, the heartbeat never dies! The timeout is ignored since the timeout doesn't apply to the `nursery` and therefore it also doesn't apply to the `nursery.start_soon()` even though that function is called inside a timeout block.

**Comment by oremanj** [comment]
I'm sorry you ran into difficulty on this!

`move_on_after()` imposes a time limit on the body of its `with` block. Since `start_soon` returns immediately, execution proceeds onward to exit the `with` block well before the timeout expires, and nothing gets cancelled.

Cancellation in Trio is implemented by raising an exception which is caught by the cancel scope (the `with move_on_after(...):` block, in this case). Even if we made the child task inherit the 5-second timeout somehow, there wouldn't be any place to catch the `Cancelled` exception that would be raised upon its expiry -- exceptions propagate out of the nursery block, not out of the call to `start_soon`, and a `with` block can't catch exceptions that aren't raised inside it. We could make the exception stop when it's about to propagate out of the task, but then you'd have no way to tell whether the timeout expired or not.

Another way to think about it: the task runs "inside" the nursery for purposes of exception propagation and timeout handling. It doesn't run "inside" the call to `start_soon`, because that call returns before the task is done running.

**Comment by RmStorm** [comment]
Hey @oremanj thanks for the explanation! I didn't properly 'get' that the `start_soon` call returns immediately and that's were my confusion came from. It makes total sense in hindsight. I think I will make a PR with a slightly expanded explanation in the docs. Because I found the relevant piece of the documentation pretty fast but it didn't actually explain what was going on.
