### ISSUE TITLE
Possible legal issues with the logo

### ISSUE THREAD

**Issue by KOLANICH** [python-trio/trio#1828]
I once wanted to use a logo in colors of python in order to highlight that my project is intended to be used with python (it is essentially python bindings to some third-party code), but feeled like they can be trademarked.

I have contacted the email and asked for clarifiaction and permission. I was told that currently they don't intend to trademark python colors and that if I start using my logo, I'd "be" a my trademark (damn this legal shit, I wish there would be no trademark laws at all!). But the colors are already a de-facto trademark.

I asked if they can either give me a digitally signed text that the use of the colors in my logo is not considered trademark violation, or change their trademark policy to clarify which uses of colors are explicitly allowed. I was answered that this is the decision which is up to the board, and the board won't do that for me unless maybe for a lot of money.

IMHO this FUD situation is a bit annoying.

https://pyright.blogspot.com/2011/02/svg-xml-and-python-logo.html
https://github.com/Nuitka/Nuitka-website/issues/19
https://github.com/PyAV-Org/PyAV/issues/728
https://github.com/derb12/mcetl/issues/13
https://github.com/ReagentX/Logria-py/issues/147
https://github.com/python-trio/trio/issues/1828
https://github.com/amcc1996/symbeam/issues/7
https://github.com/cjdoris/Python.jl/issues/3
https://github.com/fatiando/pooch/issues/222
https://github.com/aiortc/aiortc/issues/442
https://github.com/MatthijsKamstra/haxepython/issues/3

**Comment by CastixGitHub** [comment]
isn't it ok to just avoid the colors of the logo?
<details>
<pre>
$ ~  grep -e 'color' -e 'fill' python-logo-generic.svg 
     bordercolor="#666666"
     pagecolor="#ffffff"
         style="stop-color:#b8b8b8;stop-opacity:0.49803922"
         style="stop-color:#7f7f7f;stop-opacity:0"
         style="stop-color:#7f7f7f;stop-opacity:0.5"
         style="stop-color:#7f7f7f;stop-opacity:0"
         style="stop-color:#b2b2b2;stop-opacity:0.5"
         style="stop-color:#b3b3b3;stop-opacity:0"
         style="stop-color:#f4f4f4;stop-opacity:1"
         style="stop-color:#ffffff;stop-opacity:1"
         style="stop-color:#ffd43b;stop-opacity:1"
         style="stop-color:#ffe873;stop-opacity:1"
         style="stop-color:#5a9fd4;stop-opacity:1"
         style="stop-color:#306998;stop-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:#646464;fill-opacity:1"
       style="fill:url(#linearGradient1478);fill-opacity:1"
       style="fill:url(#linearGradient1475);fill-opacity:1"
       style="font-size:15.16445827px;font-style:normal;font-weight:normal;line-height:125%;fill:#646464;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;font-family:Bitstream Vera Sans"
       style="opacity:0.44382019;fill:url(#radialGradient1480);fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:20;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
</pre>
</details>

**Comment by KOLANICH** [comment]
I feel like no, but I'm not a lawer. I also think we shouldn't just avoid using them, we just should get the FUD resolved.

Also there is [an opinion](https://github.com/fatiando/pooch/issues/222#issuecomment-748048460) that as long as the project is noncommercial and is for python, the colors can be used.

**Comment by njsmith** [comment]
I'm not sure what's going on here. The text is confusing, and filing issues on a bunch of repos like this is weird? It's not even clear what trademarks you're talking about -- I assume the [PSF trademark on the official Python logo](https://www.python.org/psf/trademarks/)? And that the "email" you're talking about is the PSF trademarks committee at psf-trademarks@python.org?

If so, Trio has nothing to worry about: I checked with them when designing the logo, and they explicitly approved it. (There was actually an earlier version that they said was too similar and I had to change it. Unfortunately, they don't have as much flexibility as they would like, because of how trademark law works. Fortunately, the version we ended up with is actually better than the one they rejected, so it all worked out...)

Anyway, if you're concerned about this, then just send the actual thing you want to do and ask if it's OK, and they'll tell you. And maybe let them worry about enforcing their trademark on third parties? Filing all these issues on random projects kinda makes it look like you're trying to stir up trouble and drag people into your problem.

**Comment by KOLANICH** [comment]
The problem is that their policy (which feels like a public offer) avoids to clarify usage of the colors. I wanna them to add the clarification there. They have refused doing that for me because such decisions is not up to the person, and requires the decision by the board, and the board won't do that for just some KOLANICH from the net who asked for that. I wonder if they do that if more people ask them to explicitly clarify the situation in their policy.

>they explicitly approved it.

So did they for mine, but it feels like an informal promise not legally binding PSF not to sue me about it. I asked for something legally binding PSF (i.e. a digitally signed text that can be verified by everyone in the Net that it was issued by PSF stating which condition must be me by my project so that they don't consider that trademark infringement and won't in future, or even better, to modify their policy to address the issue), but they have refused.

**Comment by njsmith** [comment]
> The problem is that their policy (which feels like a public offer) avoids to clarify usage of the colors. I wanna them to add the clarification there. They have refused doing that for me because such decisions is not up to the person, and requires the decision by the board, and the board won't do that for just some KOLANICH from the Internet who asked for that.

Trademark law is complicated and depends on "confusability", which is highly subjective and context-dependent. They may not be *able* to make simple broad statements about whether using the colors is ok or not, because it depends on the situation.

> So did they for mine, but it feels like an informal not even a promise but an encouragement not legally binding PSF not to sue me about it

I think you're very confused about how law works. The law doesn't care about whether their email had a "digital signature" on it -- even unwritten handshake contracts can be legally binding. And anyone can sue you at any time for anything, so even if digital signatures were magic, they *still* couldn't stop you from getting sued.

At least, that's my understanding -- I'm not a lawyer. If you're really worried, then you should talk to a lawyer. They can actually help you! Spamming random projects on github can't!

**Comment by KOLANICH** [comment]
>even unwritten handshake contracts can be legally binding.

It is impossible to proove that such agreements ever existed. And in civil lawsuits it is defendant who must proove his innocence.

>And anyone can sue you at any time for anything, so even if digital signatures were magic, they still couldn't stop you from getting sued.

Yes, I know. But in some cases the plaintiff must for sure lose the lawsuite.

>And anyone can sue you at any time for anything, so even if digital signatures were magic

Digital signatures are not magic, they prove that either of the following cases has happenned:

* the entity that had signed message had signed it
* someone has gained an unathorized access to entitie's private key

>If you're really worried, then you should talk to a lawyer. They can actually help you!

Lawers cannot help with this situation, since it is in their interests the whole situation is engineered. And in their interest to have as much lawsuits as possible with as much damages as possible.

**Comment by njsmith** [comment]
Sorry, I tried to be helpful even though this is off-topic, but I don't think I can help. Let's end this discussion here.
