### ISSUE TITLE
Mention Nursery.cancel_scope in CancelScope API doc

### ISSUE THREAD

**Issue by shamrin** [python-trio/trio#1831]
A year after first learning about Trio I finally did an experiment with it. It worked great! One thing that I haven't realized is the existence of `nursery.cancel_scope`. For some time I was using explicit `CancelScope` around my `open_nursery` block.

I think it would have helped me if `CancelScope` doc would mention `Nursery.cancel_scope`. I did learn about it after I rewatched @njsmith PyCon talk.

https://trio.readthedocs.io/en/stable/reference-core.html#trio.CancelScope

**Comment by andersea** [comment]
I am not sure this belongs under cancellation, since nurseries and child tasks isn't introduced before the next chapter, however in that chapter, cancelling child tasks could probably be explained better and maybe deserves its own section. Right now the only mention of nursery cancellation is in the nursery api docs, and it is only a brief explanation.

https://trio.readthedocs.io/en/stable/reference-core.html#trio.Nursery

It is definitely an important part of the api, which is often used, so would make sense to get further treatment.

**Comment by shamrin** [comment]
It would suffice to have a short note in `CancelScope` section, linking to `trio.Nursery.cancel_scope`.

At the end I did read the full reference. However, in all other cases the manual does try to be helpful if you land in the middle of it. It often happens if you search for something specific.
