### ISSUE TITLE
How to ignore TrioDeprecationWarning only

### ISSUE THREAD

**Issue by shamrin** [python-trio/trio#1833]
I couldn't find a way to ignore `TrioDeprecationWarning` only. I get the warning while using recent trio-asyncio release (0.11), on Python 3.9:
```
.../trio_asyncio/_base.py:20: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  from trio.hazmat import wait_for_child
```

(The warning seems to be fixed in the master: python-trio/trio-asyncio#87. But the point about ignoring `TrioDeprecationWarning` still stands.)

1. I've tried `python -W ignore::trio.TrioDeprecationWarning ...`, but I got `Invalid -W option ignored: invalid module name: 'trio'` error. There is an open [Python bug about it][0].

2. I've tried [`PYTHONPATH=/full/path/to/trio` work-around][2] to fix the above, but it fails with core dump: `Fatal Python error: init_sys_streams: can't initialize sys standard streams`. There is another open [Python bug about it][1].

3. I've tried `import warnings; warnings.filterwarnings("ignore")` at my entry module, but it doesn't do anything for me.

Is there any way to ignore `TrioDeprecationWarning` only?

[0]: https://bugs.python.org/issue22543
[1]: https://bugs.python.org/issue39419
[2]: https://stackoverflow.com/a/53538033

**Comment by asmeurer** [comment]
`import warnings; warnings.filterwarnings("ignore")` works for me. I am using the following

```py
import warnings

import trio
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=trio.TrioDeprecationWarning)
    import trio_asyncio
```

The filter has to be enabled before trio_asyncio is imported. If this is difficult for whatever reason, a workaround would be to manually import `trio.hazmat` to trigger the warning. Since imports are cached in Python, the warning will only be triggered once.

(of course, with all that being said, a release of trio-asyncio that fixes this would be nice)

**Comment by shamrin** [comment]
@asmeurer Thank you for the solution!

(And, we have just [released trio-asyncio][1].)

[1]: https://github.com/python-trio/trio-asyncio/pull/94
