### ISSUE TITLE
test_ssl is very spammy

### ISSUE THREAD

**Issue by buhman** [python-trio/trio#210]
But it might still be useful to see that output if the test fails.

I played with pytest-catchlog, and while it does way more than we need (making assertions about the log messages emitted by the code being tested), the actual part where it captures the log messages seems ok:

```python
import logging

import pytest


@pytest.fixture
def log(request):
    return logging.getLogger(request.node.name)


def fake_thing():
    # imagine this being inside a module instead
    log = logging.getLogger('definitely_trio')
    log.debug('log some stuff…')


def test_raises(log):
    fake_thing()
    log.debug('before raise')
    raise RuntimeError('test')


def test_noraise(log):
    fake_thing()
    log.debug('can\'t see me')
```

```python
Test session starts (platform: linux, Python 3.6.1, pytest 3.1.1, pytest-sugar 0.8.0)
rootdir: /home/zack, inifile:
plugins: sugar-0.8.0, cov-2.5.1, catchlog-1.2.2

――――――――――――――――――――――――――――――――――― test_raises ――――――――――――――――――――――――――――――――――――

log = <Logger test_raises (WARNING)>

    def test_raises(log):
        fake_thing()
        log.debug('before raise')
>       raise RuntimeError('test')
E       RuntimeError: test

tests/test_foo.py:20: RuntimeError
-------------------------------- Captured log call ---------------------------------
test_foo.py                 14 DEBUG    log some stuff…
test_foo.py                 19 DEBUG    before raise

 tests/test_foo.py ⨯✓                                                100% ██████████
============================= short test summary info ==============================
FAIL tests/test_foo.py::test_raises

Results (0.03s):
       1 passed
       1 failed
         - tests/test_foo.py:17 test_raises
```

**Comment by njsmith** [comment]
I'm confused – for me, catching output and only showing it if the test fails is pytest's default behavior. What does this do differently?

**Comment by buhman** [comment]
> for me,

Oh. How do you run tests?

**Comment by njsmith** [comment]
> How do you run tests?

Just `pytest trio` usually – do you have `-s` configured somehow?

The appveyor ci builds also use `-s` to improve our chances of debugging weird and intermittent issues. So there's potentially some benefit to reducing unnecessary spamminess anyway.

> I think the idea is that if, outside testing, a library consumer to see the `--> transport_stream.send_all` messages, they could just by enabling trio's logger.

Those messages are generated by the test suite only (or should be, anyway!). I'm pretty sure they come from this wacky custom transport stream that I wrote to test renegotiation. Now that it's working we could potentially dial down the spamminess though.

In general there is some question of whether and how trio should log things. For the most part trio is low level enough that this doesn't come up, but there are a few places where it might be useful (logging errors in `Instrument`s, or when we get a high-level `accept` loop wrapper, logging connections dropped due to lack of resources). The problem is that the stdlib logging system is not that great, so we don't necessarily want to force our users into it. But I also don't want to create our own custom logging system, like e.g. twisted does... Probably they should be discussed on a different issue though :-)

**Comment by njsmith** [comment]
Are there still todo items here, or should it be closed?

**Comment by buhman** [comment]
I don't think there's anything specific to do here.
