### ISSUE TITLE
trio and async generators

### ISSUE THREAD

**Issue by klen** [python-trio/trio#2117]
Trio doesn't finalize async generators:

```python
async def generator(lib):
    print(f"{lib.upper()}")
    print(f"{lib} enter")
    yield
    print(f"{lib} exit\n")

import asyncio

gen = generator('asyncio')
try:
    asyncio.run(gen.__anext__())
    asyncio.run(gen.__anext__())
except StopAsyncIteration:
    pass

import curio

gen = generator('curio')
try:
    curio.run(gen.__anext__)
    curio.run(gen.__anext__)
except StopAsyncIteration:
    pass

import trio

gen = generator('trio')
try:
    trio.run(gen.__anext__)
    trio.run(gen.__anext__)
except StopAsyncIteration:
    pass

```

Output:
```
ASYNCIO
asyncio enter
asyncio exit

CURIO
curio enter
curio exit

TRIO
trio enter
```
How to force the trio to finalize the generator?

**Comment by njsmith** [comment]
There's a lot going on here :-)

So first: async generator "finalization" usually refers to an async loop explicitly forcing async generators to be closed when the loop exits. Both trio and asyncio do async generator finalization in this sense. IIRC curio doesn't, but don't quote me on that.

The interpreter support for async generator finalization was designed around the idea that you'll be creating and using your generators within a single call to `asyncio.run`/`trio.run`. By making multiple `run` calls here you're already doing something that wasn't really considered during the design, so you can to run into weird issues.

The specific detail you're running into is: asyncio/trio both try to keep track of all the open async generators, so they can finalize them when `run` exits. In order to do this, they rely on the interpreter to tell them when an async generator is created. As it happens, the interpreter does this when you call `__anext__`.

In your asyncio example, because of quirks of asyncio's API, you're calling `__anext__` *before* calling `asyncio.run`. So when the interpreter goes to notify the running loop about the async generator, it sees that there is no running loop, and doesn't tell anyone about the generator. So asyncio has no idea this generator exists, and can't finalize it when `asyncio.run` exits. Which means that it survives to be used again.

In the trio example, because of quirks of trio's API, `__anext__` gets called inside `trio.run`, after trio has started up. So when the interpreter goes to notify the running loop about the async generator, trio is there to get notified. So trio *does* know about the async generator, and cleans it up when `trio.run` exits, by calling `await gen.aclose()`. This then does `await gen.athrow(GeneratorExit)`, which causes the generator to start back up again at the `yield` statement – but it raises an exception, so your `print` statement doesn't run. Then, when you try calling `trio.run` again, the generator has *already* been finalized, so `__anext__` just raises `StopAsyncIteration` immediately.

Here's a modified example where we tweak the asyncio code so that it calls `__anext__` inside asyncio, just like the trio example – you can see that now they behave the same. Plus some extra print calls to get a clearer picture of what's happening:

```python
async def generator(lib):
    print(f"{lib.upper()}")
    print(f"{lib} enter")
    try:
        yield
    except BaseException as exc:
        print(f"{lib} exiting due to exception: {exc!r}")
    else:
        print(f"{lib} exiting normally")

import asyncio

async def do_anext():
    return await gen.__anext__()

gen = generator('asyncio')
try:
    print("first anext:")
    asyncio.run(do_anext())
    print("second anext:")
    asyncio.run(do_anext())
except StopAsyncIteration:
    print("got StopAsyncIteration")

import trio

gen = generator('trio')
try:
    print("first anext")
    trio.run(gen.__anext__)
    print("second anext")
    trio.run(gen.__anext__)
except StopAsyncIteration:
    print("got StopAsyncIteration")
```

I get:

```
first anext:
ASYNCIO
asyncio enter
asyncio exiting due to exception: GeneratorExit()
second anext:
got StopAsyncIteration
first anext
TRIO
trio enter
trio exiting due to exception: GeneratorExit()
second anext
got StopAsyncIteration
```

Does that clear things up?

**Comment by klen** [comment]
It's much more clear now. Thank you for the detailed explanation!

But I have to make separate `trio.run` calls and close the generators by myself. I came to this dirty hack:

```python
async def generator(lib):
    print(f"{lib} enter")
    yield
    print(f"{lib} exit\n")

import trio

gen = generator('trio')
try:
    trio.run(gen.__anext__().__await__)
    trio.run(gen.__anext__().__await__)
except StopAsyncIteration:
    pass
```
