### ISSUE TITLE
wait_all_tasks_blocked example correct?

### ISSUE THREAD

**Issue by remleduff** [python-trio/trio#224]
https://github.com/python-trio/trio/blob/ec4cdee7de14ede9fdd8b863af54510c714be99d/trio/_core/_run.py#L1089

When I try to run this example, I get an AssertionError, I believe on the linked line.

Reading the code, I can't tell why we expect the lock to be unlocked at that point when we acquired the lock before entering the "async with" block, but I'm unsure if I'm misunderstanding part of the trio API.

**Comment by njsmith** [comment]
Uh.... No, it looks like a silly mistake on my part. I think that assertion should just be deleted. (And also the next one, the `assert lock.locked()` – that one should pass at least because it's vacuously true, but it's not making the example any clearer.) Good catch, thanks!

I wonder if there's a better example – that one's pretty subtle. I think it's there because it was literally the problem that pushed me to implement `wait_all_tasks_blocked`, but since then I've started using it all over the place...
