### ISSUE TITLE
"Google Docstring Format" link goes to 404

### ISSUE THREAD

**Issue by BruceEckel** [python-trio/trio#2546]
Under this header: https://trio.readthedocs.io/en/stable/contributing.html#documentation
At the beginning of the 2nd paragraph: "For docstrings, we use [the Google docstring format](https://www.sphinx-doc.org/en/3.x/usage/extensions/example_google.html#example-google-style-python-docstrings)."

The link goes to a 404 page.

**Comment by A5rocks** [comment]
It looks like v3 of the Sphinx docs was pulled? This link certainly works: https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google-style-python-docstrings

I think we should probably check the old link 404ing is intentional. In the meantime, updating the docs should be simple.

**Comment by kachida** [comment]
Hi @A5rocks , I've created a pull request (PR#2967) for this issue. Could you please take a look and review it

https://github.com/python-trio/trio/pull/2967
