### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [python-trio/trio#2655]
Could you please make a new release? I'm specifically looking for the `async_generator` dependency being removed, as that should be good enough to enable Python 3.12 support in the Gentoo package.

**Comment by mgorny** [comment]
I've seen only 1 new test fail on Gentoo compared to Python 3.11  (`trio/_core/_tests/test_run.py::test_nursery_cancel_doesnt_create_cyclic_garbage`). I'm yet to see in greater detail but it seems good enough for httpx at a first glance.

I'm currently playing with a snapshot from current git, so hopefully that'll be good enough before the next release.

**Comment by bastimeyer** [comment]
Hi, would it be possible to publish a new release before waiting for the support end of Python 3.7? I don't care about 3.7, but the last release of trio was in September of last year, which is quite a while.

I'm specifically looking for support for generic typing of `MemorySendChannel`/`MemoryReceiveChannel` which was added in #2549 in February.

The most recent release of `trio-typing` already defines

```py
class MemorySendChannel(trio.abc.SendChannel[T_contra]): ...
class MemoryReceiveChannel(trio.abc.ReceiveChannel[T_co]): ...
```

This just bit me a bit as a new user of trio, because I thought that this was supported. Right now I get this error when trying to implement generic memory channels:

> TypeError: <class 'trio.MemorySendChannel'> is not a generic class

```py
class EventListener(Generic[TEvent]):
    sender: trio.MemorySendChannel[TEvent]
    receiver: trio.MemoryReceiveChannel[TEvent]
    ...
```

Installing trio from git is not an option for me, so I'm kindly asking for a new release. Thanks!

**Comment by oremanj** [comment]
3.7 EOL is in two weeks. I won't personally be able to roll a new release before that, but maybe someone else will.

You can use `from __future__ import annotations` to resolve the MemoryXyzChannel-not-generic error.

**Comment by A5rocks** [comment]
Only https://github.com/python-trio/trio/pull/2674!

**Comment by A5rocks** [comment]
Oh yeah, and pylint failing on pypy-3.7 isn't great, since the required checks need to pass before releasing. I've left a comment on https://github.com/python-trio/trio/pull/2669 cause I think you could xfail it there or maybe you (or I) could make a seperate PR.

**Comment by jakkdl** [comment]
:rocket: :rocket: :rocket:

**Comment by mgorny** [comment]
Thanks!
