### ISSUE TITLE
Add static analysis support to _util.Final

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2683]
See discussion in https://github.com/python-trio/trio/pull/2668#issuecomment-1607558210

`@final` was added in 3.8, so it would be good to make classes decorated with `_util.Final` also be treated as `@final` by type checkers. I didn't find a good way of applying both with a single decorator or metaclass, so unless I missed a way we might have to have both on all classes. Or possibly skip one of them.

**Comment by A5rocks** [comment]
Might be a nice case for just a lint to ensure we have both? I can't think of a solution here unfortunately.

**Comment by TeamSpen210** [comment]
There is actually a better way, but it'd require some churn. By using `__init_subclass__`, we [can implement](https://github.com/python-trio/trio/commit/b6c4089d6066047bb18814980a8ac8e0eb743466) `_util.Final` as a decorator. Then we can just make it an alias to the `typing` version `if TYPE_CHECKING`. A decorator's better anyway since we don't have to worry about metaclass conflicts. 

The biggest downside is that we have to remember to use `@final` alongside `NoPublicConstructor`, since I can't think of a way to make the latter a decorator. We could fairly easily add a check to the `test_exports` logic to look for these cases though.

I don't think we need to care about backwards compatibility, since these are both private.

**Comment by jakkdl** [comment]
Sounds like a decent enough solution to me :+1:
