### ISSUE TITLE
Identify an SSL connection from a client that may be non-SSL

### ISSUE THREAD

**Issue by ghost** [python-trio/trio#2684]
I am writing a CONNECT proxy server and when I connect to an SSL port on the iIRC server the connection with the proxy is SSL encrypted as-well. But when I connect to a normal non-SSL port on the IRC server then the data with the proxy server is not encrypted. I could have specific ports on the proxy server for SSL-only however, a more convenient way is, if I could detect an SSL connection on the client, and still have it work, would be best.  That way I could double-wrap the socket and everything would be okay,

**Comment by ashburry-chat-irc** [comment]
The SSL detection may have to be in mid-connection it just switches to SSL. I am trying to connect to irc.dal.net:6697 but it starts out with plain text then swtiches to SSL (as far as I can tell) Trio does not support this from what I have read. Please fix Trio so I can connect to DALnet on SSL.

**Comment by A5rocks** [comment]
(my perspective is someone who uses Trio for concurrency uses and very much a networking noob!)

I'm ~~a bit~~ very confused about this issue. My understanding of TLS is that it has to be done upfront and you can't change mid-connection; for instance, the higher level protocol might tell you to reconnect.

I was wondering what exact API you were looking at in trio, if you have any reference for how things could be, and whether the protocol is simple enough that you could detect non-protocol data and assume TLS (I don't know CONNECT proxies, my only experience was SOCKS5 proxies years ago and I forgot everything :P). Sorry if this is all obvious to you!

**Comment by smurfix** [comment]
One real-world example you might want to look at is CUPS, the print server. You can talk to it with `https`. Or `http`. Same port.

This works because the server can look at the initial data from the client; it checks whether that's ASCII or a TLS packet. It might be useful to write a stream protocol that does this; just add an `async def is_encrypted()` method that waits for initial data and either buffers it or feeds it to TLS if it doesn't yet know. Same for the initial `receive` call.

That being said, this can well be a standalone add-on. No need to add this to Trio proper.

**Comment by ashburry-chat-irc** [comment]
Thanks smurfix, your are right about http and https on the same server and port however I have learned that when connecting the tls to a server and you have a proxy server inbetween the encryption fails because because the connection is started at client A then Client B is making the connection when client A was not connecting to client B it was connecting to Server A from Client A. I just have it auto SSL from proxy to irc server based on ports and no SSL/TSL to the proxy server or irc server from client A.

**Comment by ashburry-chat-irc** [comment]
> One real-world example you might want to look at is CUPS, the print server. You can talk to it with `https`. Or `http`. Same port.
> 
> This works because the server can look at the initial data from the client; it checks whether that's ASCII or a TLS packet. It might be useful to write a stream protocol that does this; just add an `async def is_encrypted()` method that waits for initial data and either buffers it or feeds it to TLS if it doesn't yet know. Same for the initial `receive` call.
> 
> That being said, this can well be a standalone add-on. No need to add this to Trio proper.

The problem with this is I need to read non encrypted data, I can already detect encrypted data but cannot read it but can make a valid socket with the reads/writes on non-SSL sockets with SSL/TLS data.

**Comment by ashburry-chat-irc** [comment]
> (my perspective is someone who uses Trio for concurrency uses and very much a networking noob!)
> 
> I'm ~a bit~ very confused about this issue. My understanding of TLS is that it has to be done upfront and you can't change mid-connection; for instance, the higher level protocol might tell you to reconnect.
> 
> I was wondering what exact API you were looking at in trio, if you have any reference for how things could be, and whether the protocol is simple enough that you could detect non-protocol data and assume TLS (I don't know CONNECT proxies, my only experience was SOCKS5 proxies years ago and I forgot everything :P). Sorry if this is annoying to answer!

**### Reply:**
You are right SSL/TLS is an upfront encrypted protocol. You can detect TLS in a plain socket and even read all the encrypted data but you cannot change nor read any of the text. So a non-encrypted connection to the proxy server is used and an encrypted connection from the proxy to the irc server (port may change). The main reason why I use Trio is because Python forgot to include a run command for their async/await function call that starts the app. Also the usage of nurseries is far more useful than trying to program random async/await functions that do not properly follow one function in order after another in order. Instead you always have the latest function execute in that order and all you need to do is create nurseries. Trio can become very complex but I just use the simple parts of it because that is all I understand but I understand that is all I need to know.

**Comment by Ashburry-trio** [comment]
You can change a regular TCP socket to encrypted using STARTTLS it is for TCP connections that are already open and unencrypted.

**Comment by Ashburry-trio** [comment]
If i was just reading socket data and forwarding it without the need to decrypt I could have TLS port share a regular, non-encrypted, port number. But I need to read and change the text before sending it off to the server.

**Comment by Ashburry-trio** [comment]
@smurfix sday hi

**Comment by CoolCat467** [comment]
I am going to close this, as the original commenter deleted their account.
