### ISSUE TITLE
Cython has defeated our Cython workaround

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#2908]
When we spawn a task, we inject a magic local variable into the top stack frame's local namespace, as part of our tricky control-C magic:

https://github.com/python-trio/trio/blob/d4ce2f9e42c386f1b64969f0495fafe2a2183b22/src/trio/_core/_run.py#L1753

However, this doesn't work for `async def` functions defined in C or Cython, because they don't have a Python frame. So we a simple workaround, we detect this case and inject a no-op Python frame where we can insert our magic local (cf #550):

https://github.com/python-trio/trio/blob/d4ce2f9e42c386f1b64969f0495fafe2a2183b22/src/trio/_core/_run.py#L1747-L1750

However, the bug came back at some point with newer versions of Cython:

```
             |   File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/trio/_core/_run.py", line 1599, in spawn_impl
             |     coro.cr_frame.f_locals.setdefault(LOCALS_KEY_KI_PROTECTION_ENABLED, system_task)
             |     ^^^^^^^^^^^^^^^^^^^^^^
             | AttributeError: 'NoneType' object has no attribute 'f_locals'
```

From the error message, it appears that Cython has added a `cr_frame` attribute to its fake coroutine objects... just it's `None`. So it's still not really there, but it's enough to sneak past our `hasattr(coro, "cr_frame")` test.

I think the fix here is just to replace the `if not hasattr(coro, "cr_frame"):` with `if getattr(coro, "cr_frame", None) is None:`. But it would be good to also run a test for this in CI. We do have a test for the interpreter's built-in C coroutines (`test_async_function_implemented_in_C`) and I originally assumed that would be enough, but obviously it wasn't, so I guess we need to do the legwork to install cython in CI and build a tiny Cython module.

Edit by CoolCat467:
Things to do:
- [x] Fix existing issue (#2911 is handling)
- [ ] Add CI runner for cython so this sort of thing doesn't happen again in the future

**Comment by TeamSpen210** [comment]
This might be fixed in newer versions potentially. Found this issue: https://github.com/cython/cython/issues/2306. As of 3.0, `cr_frame` should actually produce a valid frame object. Locals will be null but it looks like accessing it will make a dict for us.

To test different versions of Cython, we could make a test module, then manually compile it with historical versions and commit the C files to our repo. Build those in CI and test, plus a version where we compile with latest to check it still works. In the future those will eventually stop working with new Python releases, in that case we can start skipping and eventually remove when we also stop supporting those versions.

**Comment by jakkdl** [comment]
> This might be fixed in newer versions potentially. Found this issue: [cython/cython#2306](https://github.com/cython/cython/issues/2306). As of 3.0, `cr_frame` should actually produce a valid frame object. Locals will be null but it looks like accessing it will make a dict for us.

After some struggling I did manage to repro this, and it only happens cython<0.29.24 (released 2021-07-14). 


> To test different versions of Cython, we could make a test module, then manually compile it with historical versions and commit the C files to our repo. Build those in CI and test, plus a version where we compile with latest to check it still works. In the future those will eventually stop working with new Python releases, in that case we can start skipping and eventually remove when we also stop supporting those versions.

Even making a trivially short pyx test file I'm getting it compiled into a c file that is 223kb, although maybe there is a way of trimming that down. So I think we'd need to do the building as well to not drown in all of it. But we probably don't want to test all versions since 0.29.24 (23, not including alpha/beta/rc releases) either way and should choose a select number of them.

How far back do we want to support?

**Comment by A5rocks** [comment]
Personally, I think just checking start and end of supported versions is fine. (and it's fine not to do that on every platform we support -- we can only run so many gh actions concurrently :( )
