### ISSUE TITLE
Asymmetric test in trio/testing/_checkpoints.py

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#329]
The test for whether a code yielded isn't the inverse of whether it didn't yield, in `trio/testing/_checkpoints.py:_assert_yields_or_not`.

One of these needs to be fixed, but I'm not sufficiently versed in Trio internals to figure out which.

Idea: factor this out to a `yielded` bool, then write the conditional as `if expected and not yielded` … `elif yielded and not expected` clauses.

**Comment by njsmith** [comment]
That's intentional – a "yield" (which has now been renamed "checkpoint") is two things: a schedule point and a cancel point. In general they are supposed to happen together, but a test function has to assume that the code it's testing might be buggy, so `assert_yields` is written to assert that both a schedule point and a cancel point happen, and `assert_no_yields` is written to assert that neither happens. (And if just one of them happens, then that's a bug, and they both raise an error on that.)

However, I couldn't come up with any real uses for `assert_no_yields`. And discussing this is sorta pointless without a use case – first because it's impossible to say if it's doing what we want when we don't know what it's supposed to be accomplishing, and second because I deprecated it :-)

Do you have a use case for `assert_no_yields`?

**Comment by smurfix** [comment]
Actually, I do have a usecase for `assert_no_yields` – a fairly complicated do-some-of-the-actual-work procedure in a project I plan to convert to Trio. If there is in fact no work queued then this method should in fact return quickly – and without hitting a checkpoint.

**Comment by njsmith** [comment]
#352 un-deprecates `assert_no_yields` (aka `assert_no_checkpoints`), and hopefully the semantics are clear after the explanation above? Feel free to re-open if not.
