### ISSUE TITLE
TypeError: cannot create weak reference to 'Lock' object

### ISSUE THREAD

**Issue by henry232323** [python-trio/trio#331]
`trio.Lock` objects cannot be WeakReferenced! Is there a way we could get this fixed?

**Comment by njsmith** [comment]
Huh, well, that's bizarre, and certainly not intentional. I suspect this is because they use `__slots__` (via `attr.s(slots=True, ...)`), and probably affects a bunch of classes.

Ah-hah, yep: https://github.com/python-attrs/attrs/issues/174

The simplest solution would be to go remove `slots=True` everywhere, since it's kind of a vague premature optimization in the first place...
