### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by henry232323** [python-trio/trio#338]
**https://hacktoberfest.digitalocean.com/#resources**
**https://hacktoberfest.digitalocean.com/**
Considering registering Trio for Hacktoberfest?

**Comment by njsmith** [comment]
Huh, interesting idea!

I think right now though I'd better focus available energy on finishing up the 0.2.0 release and this contributing document I've been working on, since right now growing the community is sort of bottlenecked on me doing things. If that gets done before the end of October though, then maybe we can join in for the end :-)
