### ISSUE TITLE
"Some thoughts on asynchronous API design ..." hushes about asyncio.wait_for()

### ISSUE THREAD

**Issue by pfalcon** [python-trio/trio#360]
This is more about "bug report" for https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/ , but for the lack of better place, let me do that here.

So, nowhere the https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#timeouts-and-cancellation section, or the entire article, mentions asyncio.wait_for() function for timeouts. This may give an impression to a careless reader that asyncio doesn't offer (good) timeout facilities. But well, it does, and it works pretty much as described in that section, except that, well, it requires factoring out the functionality into a separate function instead of allowing intra-function chunks with a context manager. 

(Submitted after seeing this comment https://github.com/dabeaz/curio/issues/149#issuecomment-269604401 , hinting that there may be just a personal preference for context managers ;-).

**Comment by njsmith** [comment]
I'm not sure now whether I was aware of `wait_for` at the time I wrote that section (it's certainly confusingly named!). But looking it over, I don't think that section looks too bad? I point out that asyncio can implement the full-fledged context manager approach and link to such an implementation, so I hope it doesn't give the impression that asyncio can't do cancellation at all. The bulk of the section (like the bulk of the blog post) is about how combining the async/await layer and the `Future` layer creates complications, because you end up with two different cancellation systems and need to somehow shim them together. Really the point I'm making is that asyncio has *too much* support for cancellation :-)

I'm actually working on a blog post now that reviews the space of approaches to timeouts/cancellation and talks about why trio makes the choices it does – hopefully it will be ready within the next week or two.

**Comment by pfalcon** [comment]
> (it's certainly confusingly named!)

Really? And I find its naming very natural - it indeed waits for result within specified period of time. Also, "computation model" of it is very natural - a good look at a timeout as an error, so exception is raised, the same as in sync code would do. Yes, it can be recovered (sometimes), and context manager can be built on top of it, but asyncio exactly exposes the proper API level to do all that.

Vice versa, I find both naming and semantic of Trio's move_on_after() to be not natural - it swallows error, and leaves a user with `if`'s on random variables to check whether it happened. (Somehow, move_on_after() is the first thing re: timeouts I saw in Trio. I grepped the tutorial and see that "move_on_after" isn't even there! Instead, it has TODO for fail_after(). Weird where I picked up that move_on_after()).

**Comment by njsmith** [comment]
> I find its naming very natural - it indeed waits for result within specified period of time

My complaint about its name is that in `await foo()` versus `await wait_for(foo(), 60)`, the `await` is what does the waiting, and the complete and only purpose for `wait_for` is to add a timeout. So shouldn't the name say something about timeouts? It's not at all obvious if you're skimming the docs trying to figure out how to add a timeout :-).

> `move_on_after()`

The problem with exceptions is that they don't compose well. Suppose you have multiple nested cancel scopes. An exception could tell you that some timeout somewhere expired, but it doesn't tell you whether it's the particular timeout you wanted to check for.

I played around with some options that use exceptions, but it just makes things even messier. Like compare:

```python
with move_on_after(60) as cancel_scope:
    await foo()
if cancel_scope.cancelled_caught:
    await recover_from_foo_timeout()
```

to some mess like

```python
try:
    with move_on_after(60) as cancel_scope:
        await foo()
except TimeoutError as exc:
    if exc.cancel_scope is cancel_scope:
        await recover_from_foo_timeout()
    else:
        raise
```

Also, `move_on_after` semantics turn out to be useful surprisingly often. Basically it's the cases where you're like "whatever, I don't care about this anymore, so forget about it" – it's not an error, you just want to move on. And the low-level cancellation semantics work this way, just because when you want to have two options, one that does something and one that doesn't, it's usually easier to build the do-something option on top of the do-nothing option, rather than vice-versa.

But yeah, if you want the "set a timeout and throw an error if it expires" then `fail_after` does that for you.
