### ISSUE TITLE
using a nursery without a context manager?

### ISSUE THREAD

**Issue by lilydjwg** [python-trio/trio#402]
I'm writing a class that will spawn tasks during its lifetime. I'd like to have a `self._nursery` so that I can spawn tasks and let it run (e.g. a heartbeat task). But it seems that the nursery can only be used in a context manager, so it closes in the same scope it gets created. I don't want to pass in a nursery from outside because it's an implementation detail.

How should I write such a thing, which has background tasks during its lifetime?

**Comment by njsmith** [comment]
Excellent question!

So, one of Trio's weirdest, most controversial decisions is that it takes the position that the existence of a background task is *not* an implementation detail, and *should* be exposed as part of your API. On balance I think this is the right decision, but it's definitely a bit experimental and has some trade-offs.

Why does Trio do this? In my experience, other systems make it seem like you can abstract away the presence of a background task or thread, but in reality it leaks in all kinds of ways: they end up breaking control-C handling, or they cause problems when you're trying to exit the program cleanly, or they leak when you try to cancel the main operation, or you have sequencing problems because the function you called completed but the work it promised to do is still going on in the background, or the background task crashes with an unexpected exception and then the exception gets lost and all kinds of weird problems ensue... so while it might make your API feel a little messier in the short term, in the long term everything goes easier if you make this explicit.

Also, keep in mind that everyone else writing and using Trio libraries has the same issue, so your API is not going to feel too weird :-).

I don't know what you're trying to do exactly. Maybe it's something like a websocket connection, where you want to constantly be reading from the socket to respond to heartbeat ("ping") requests. One pattern would be to do something like:

```python
@asynccontextmanager
def open_websocket(url):
    ws = WebSocket()
    await ws._connect(url)
    try:
        async with trio.open_nursery() as nursery:
            nursery.start_soon(ws._heartbeat_task)
            yield ws
            # Cancel the heartbeat task, since we're about to close the connection
            nursery.cancel_scope.cancel()
    finally:
        await ws.aclose()
```

And then your users can use it like:

```python
async with open_websocket("https://...") as ws:
    await ws.send("hello")
    ...
```

If you want to get fancier, another option would be to provide one version where your users pass in their own nursery, for experts:

```python
class WebSocket(trio.abc.AsyncResource):
    def __init__(self, nursery, url):
        self._nursery = nursery
        self.url = url

    async def connect(self):
        # set up the connection
        ...
        # start the heartbeat task
        self._nursery.start_soon(self._heartbeat_task)

    async def aclose(self):
        # you'll need some way to shut down the heartbeat task here
        ...
```

and then also provide a convenience API, for those who just want one connection and don't want to mess with nurseries:

```python
@asynccontextmanager
async def open_websocket(url):
    async with trio.open_nursery() as nursery:
        async with WebSocket(nursery, url) as ws:
            await ws.connect()
            yield ws
```

The main advantage of the pass-in-a-nursery approach is that if your users want to open lots of websocket connections, an arbitrary number of websocket connections, then they can open one nursery once at the top of their websocket management code, and then have lots of websockets inside it.

You're probably wondering, though: where do you find this `@asynccontextmanager`? Well, it's included in the stdlib in 3.7, but that's not even out yet, so you're probably not using it. I guess we need something better. Probably the solution is to take the version from the 3.7 stdlib, and put it into the [`async_generator`](https://github.com/njsmith/async_generator) library. If you'd like to do a PR for that, then excellent :-). Otherwise I'll get around to it as soon as I can...

-------

As a side note: can I ask a favor? would you mind reposting this question to StackOverflow (and then I'll re-post the answer)? I want to start seeding some questions over there where it'll be easier for folks to find them, get the `trio` tag set up, etc., and this would be a perfect StackOverflow question :-).

**Comment by lilydjwg** [comment]
Thanks! I'll go the contextmanger way for the moment. (It's somewhat like `async` keyword, once you get it, you can't escape.)

Yes I'm looking for `@asynccontextmanager`. There is one at `@trio._util.acontextmanager` but it's private.

I don't have enough reputations to create the `trio` tag...

**Comment by njsmith** [comment]
> I don't have enough reputations to create the `trio` tag...

If you post without the tag (you can use `python` if you need a tag), then post the link, I think I can add it for you afterwards...

**Comment by lilydjwg** [comment]
OK, [question](https://stackoverflow.com/questions/48282841) posted.

**Comment by pquentin** [comment]
Unfortunately @mjpieters put the question on hold. I guess that the same question needs more context on Stack Overflow to make it clear that the question is actually very specific and is a really good question!

**Comment by njsmith** [comment]
@lilydjwg I edited the question to hopefully make it clearer, and trigger a re-review. Please check that I haven't misrepresented you by changing your words!

If anyone reading this has 3000+ reputation on stackoverflow, please feel free to vote to re-open that question :-)

**Comment by mjpieters** [comment]
Thanks for editing that question; indeed, the context about Trio was missing (I see now it was there in the title but the name is rather.. generic for that to stand out).

I'm going to *remove* the `trio` tag however, and add a `python-trio` tag. The name `trio` is just too generic to stand a chance of survival, long term, on Stack Overflow. You may want to update your tutorial to use that tag.

**Comment by njsmith** [comment]
Martijn came back and re-opened it (thanks!), so the SO thing is all sorted now.

**Comment by njsmith** [comment]
@lilydjwg BTW I just released a new version of `async_generator` that has `@asynccontextmanager`

**Comment by lilydjwg** [comment]
@njsmith Thanks!
