### ISSUE TITLE
Explicitly pass the event-loop around instead of treating it as global

### ISSUE THREAD

**Issue by catern** [python-trio/trio#426]
If trio classes and code supported explicitly passing in the lower-level functions that actually perform yields back to the event loop, they would be event-loop independent.

Essentially this is the same issue as https://github.com/dabeaz/curio/issues/248

I admit I haven't looked closely enough at trio code to be able to find a good example like I mentioned in that Curio issue, sorry.

**Comment by njsmith** [comment]
There is no event loop object in trio, and asyncio has been jumping through hoops to remove explicit loop passing as much as possible, since users dislike it so much. But I guess this doesn't actually matter for your request anyway? It sounds like you don't actually care about the manual passing per se; you'd just as happy with implicit passing, so long as it let you choose which loop was implicitly passed?

The larger problem is that different libraries actually work differently. If trio had an event loop object, its methods would have a totally different API then all the other libraries. In curio, any operation that wakes up a task has to be marked async (e.g. `Lock.release` or `Event.set`); in trio this would be a very weird thing to do. In trio-asyncio, we have to have explicit functions `run_trio`, `run_asyncio` to pass between the two sets of semantics, because the cancellation systems work differently and we need to translate between them. I suspect any API that tries to silently paper over these kinds of differences is going to end up making a lot of compromises and feel weird everywhere; I'd rather trio's builtins focus on taking full advantage of trio's in unique approach.

That said, you certainly can try building this kind of event-loop interface if you want – it doesn't have to be built into trio/curio/whatever to work. (Obviously, since the whole point is that it should work even when it's not native :-).) The `multio` library is one attempt along these lines that I know of. I know @SunDwarf has used and worked on it – they might be able to give you some thoughts on the approach.

**Comment by catern** [comment]
That's understandable. The trio code appears more tied into the GLOBAL_RUN_CONTEXT than curio's fairly generic code, so it would be harder to make trio's socket class (for example) accept all the things it needs as arguments.

Note that the issue isn't quite the same thing as making a generic interface to multiple asynchronous IO libraries, like multio. It's more about allowing a modular approach to constructing new asynchronous IO libraries, by allowing components to be reused. The fact that trio has different low-level semantics from other libraries doesn't matter - one would only use components from trio if one was building a library which had similar low-level semantics.

**Comment by njsmith** [comment]
Ah, I see. Well, if you want to fork trio, it's allowed by the license, so have fun and all that. Beyond that, providing tools to build new async IO libraries is *definitely* outside trio's scope. We already have too many async IO libraries :-).

Obviously as the author of a new async IO library, I don't have a ton of credibility when arguing that people shouldn't make new async IO libraries. But it's true. For most types of libraries, it doesn't really matter how many competing versions there are, everyone can just pick their favorite and it's fine. But an async library is useless without an ecosystem of downstream libraries that integrate with it, and these incompatible ecosystems are competing for a limited pool of developer attention, so every new async library arguably makes Python as a whole weaker by splitting up developers into smaller and smaller pools. We're all better off if there's just one library that everyone uses.

I work on trio anyway because I think it has such dramatic benefits over other libraries that it can make up for this cost, and has a non-zero change of becoming that dominant library; obviously that's my ideal outcome. But if that doesn't work out, I'd rather trio fizzle out than that it become one of a dozen competing libraries that all have sucky ecosystems – at that point it wouldn't be helping anyone.

And in any case, implementing `trio/_socket.py` or `trio/_sync.py` is like 0.01% of the work involved in making a real async library, so I don't think providing reusable tools here is actually that helpful anyway. If you're just playing around, then implementing that stuff is part of the fun. And if you want to work on a serious async library that has the same low-level semantics as trio, then why not work on trio? [We're friendly :-).](https://trio.readthedocs.io/en/latest/contributing.html)
