### ISSUE TITLE
Wait for a concurrent.futures.Future

### ISSUE THREAD

**Issue by miracle2k** [python-trio/trio#468]
An existing asyncio code base of mine needed a new background task, and I thought, hey, let me see what happens if I try to write that in trio. So I basically have two threads going, one running the asyncio loop, another running trio. Now I want to call from one to the other. Say I want to call into trio, and wait in asyncio.

I can't use `BlockingTrioPortal` for this, because it would block my asyncio thread. Going on level further down, I can see there is ``TrioToken.run_sync_soon``, which seems quite handy, it allows me to say:

```python
async def call_inside_trio(trio_token, f, *a, **kw):
    future = concurrent.futures.Future()
    def call_this_interop():    
        future.set_result(f(*a, **kw))
    trio_token.run_sync_soon(call_this_interop)
    await asyncio.wrap_future(future)
```

Because two threads are involved, I should probably use a threading-based ``Future`` class. Good that asyncio has this handy ``asyncio.wrap_future`` helper that converts the ``concurrent.futures.Future`` object to an ``asyncio.Future`` one.

Now what if we want to go the other way around? Calling a function inside the asyncio thread, and blocking within trio for the result?

Before figuring out the asyncio part, I actually noticed that curio supports a trap that can deal with a threading Future (https://github.com/dabeaz/curio/blob/a3e629da67a67e87cef7d026e5d355e9dd5e3179/curio/workers.py#L69), which I think would be a solution to this problem.

And looking at Trio's ``run_sync_in_worker_thread``, I could imagine myself building something by following along how it uses``wait_task_rescheduled`` (but skipping the part where an actual thread is created, instead resuming once the future result is ready - https://github.com/python-trio/trio/blob/0db92590aa092b8b9988d8120bf9591f95d77f79/trio/_threads.py#L398). It seems a bit involved though.

I suppose I am wondering if I am approaching this right, if I missed some already existing solution, of if anyone with more experience has a better idea. To be clear, I want do to this:

```python
async def foo():
     return 1

async def main():
     await call_in_async_io(foo)

start_asyncio_thread()
trio.run(main)
```

And specifically, I can implement ``call_in_async_io`` by returning a ``concurrent.futures.Future``, so I need trio to wait on that.

**Comment by njsmith** [comment]
Hey, thanks for checking out Trio! A few different thoughts here.

First, you should be aware of @smurfix's [trio-asyncio library](https://trio-asyncio.readthedocs.io/en/latest/), which lets you run asyncio code under trio and call back and forth, all in a single thread. (And in particular, using trio-asyncio means that you have the normal [nice cooperative scheduling guarantees](https://glyph.twistedmatrix.com/2014/02/unyielding.html) even if the trio code and asyncio code are both touching the same data structures. Using two threads can work too, but it means now you're doing thread programming with everything that comes with that.)

Second, regarding the question in the title of your issue, there's a little example here of how you might use trio and `concurrent.futures` together: https://gist.github.com/njsmith/be24d376faea61cb3999f08318b780f3 (untested). I *don't* think this is really relevant to your actual goal, but mentioning it anyway out of general interest and in case people looking for that start finding this issue through search engines :-).

Finally, for the real question, about calling back and forth between a trio thread and an asyncio thread. This is definitely doable. It's also a lot of gnarly glue code, because we're dealing with threads, and two different async libraries, and trying to adapt between their different abstractions. What makes it particularly tricky is hooking up their cancellation systems, so that if we cancel a call on the asyncio side then it propagates that to the trio side and vice-versa. It's an interesting challenge actually! If we want cancellation to work properly then I don't think we can use `concurrent.futures.Future`, but that's OK; we can use similar techniques to how `BlockingTrioPortal` is implemented, but using `loop.call_soon_threadsafe` / `token.run_sync_soon` to get back and forth instead of using blocking calls.

Anyway, I took a shot at it, and I think the basic approach should work: https://gist.github.com/njsmith/14502e2c41bcbdc409c3d5bc9f49a5b5. Unfortunately it's untested because that's as far as I got and I'm going to bed now, but if asyncio-trio doesn't work for you then maybe give it a try and let us know how it goes :-).

**Comment by miracle2k** [comment]
The reason I am attracted to Trio is because I feel that things like exception propagation, cancellation and so on are really thought through, and I can see why that is, looking at the last gist. That's a lot of code! Thanks a ton for putting it together, it was helpful for me and I am sure it will come in useful for others too.

It seems in terms of the broad strokes I got it correctly. What I suppose what I was after was:

- Is using ``wait_task_rescheduled`` ok? (Yes it is)
- Should there be better/easier primitives that allow me to implement a ``call_inside_asyncio`` (similar to the pretty short and obvious ``call_inside_trio`` function I posed above)? Probably not - using ``wait_task_rescheduled`` turns out to be *fairly* straight forward, as in your second Gist. Unless you want to propagate cancellations, in which case there is likely no way to avoid the complexities that come with it, and I probably don't want to implement it myself, and instead use the portal you posted.

I was struggling to figure out how to run an async function inside trio from the outside, since ``run_sync_soon``only supports sync functions. You are using:

```
def trio_side_sync_helper():
     trio.hazmat.spawn_system_task(foo)

trio_token.run_sync_soon(trio_side_sync_helper)
```

Which in terms of the API seems fair enough.

I note that for calling from asyncio to trio, you are using ``loop.call_soon_threadsafe`` to bring the result back to the asyncio thread, whereas I was going to use a thread-safe ``concurrent.futures.Future`` (with ``asyncio.wrap_future``), which also works. I suppose same difference, but if there is more behind your choice I'd be interested to know.

**Comment by smurfix** [comment]
IMHO a better way to spawn tasks into the Trio thread would be a job submission queue that's processed by a Trio task you spawn. The advantage is that you can use your own nursery for that, allowing you to shut them all down cleanly, which is somewhat important when you want to compose your code with others.

In any case I'd investigate using trio-asyncio instead of two threads. That's why I wrote it after all. ;-)

**Comment by njsmith** [comment]
> Is using `wait_task_rescheduled` ok? (Yes it is)

Yeah, you do have to be careful because it exposes some of the raw complexities of async concurrency and doesn't have a lot of guardrails, but this is a case where we're trying to bootstrap some friendly easy-to-use helpers out of nothing, and that's exactly what `wait_task_rescheduled` is intended for.

I can see an argument for including `AsyncioTrioPortal` inside trio -- the main reason I haven't is that I think the trio-asyncio approach is probably better for most users (I think?), and I don't want to confuse people. Even if it doesn't end up in trio itself, then throwing it into another library on PyPI would make sense. It's definitely the sort of thing where one person should implement it once, get it right, and then no-one ever has to look at it again :-).

> I was struggling to figure out how to run an async function inside trio from the outside, since `run_sync_soon` only supports sync functions.

Yeah, this is again because these very-lowest-level tools are as minimal and orthogonal as possible. This is good in some ways, but does make it harder to figure out what you need :-). One trick is to [look at how `BlockingTrioPortal` does it](https://github.com/python-trio/trio/blob/aee2676fd5096daf2849db9756242a30e0aa1f30/trio/_threads.py#L63), but admittedly `BlockingTrioPortal` is also pretty confusing if you don't already know how it works...

>I note that for calling from asyncio to trio, you are using loop.call_soon_threadsafe to bring the result back to the asyncio thread, whereas I was going to use a thread-safe concurrent.futures.Future (with asyncio.wrap_future), which also works. I suppose same difference, but if there is more behind your choice I'd be interested to know.

Yeah, either way would probably work. If you look at [how `wrap_future` is implemented](https://github.com/python/cpython/blob/c2b0b12d1a137ada1023ab7c10b8d9a0249d95f9/Lib/asyncio/futures.py#L326-L375), you'll notice that at the end of the day it ends up [calling `loop.call_soon_threadsafe` to resolve an `asyncio.Future`](https://github.com/python/cpython/blob/c2b0b12d1a137ada1023ab7c10b8d9a0249d95f9/Lib/asyncio/futures.py#L359). Since I know this, it felt simpler to just do it myself :-). Also, some of the other ways I use `call_soon_threadsafe` would be more difficult to replace with `wrap_future`. But yeah, for `run_trio_from_asyncio` both ways of doing it are basically equivalent.

-----

@smurfix ah, true, that code I wrote doesn't think at all about how you want to manage the lifetime of the trio thread.

Basically, it assumes you've somehow started a thread running `trio.run`, that you've gotten that `run`'s `TrioToken`, that you've set up some mechanism for keeping the call to `run` sitting idle indefinitely, and that you have some way to shut it down when you're done. For example, you might do something like:

```python
async def trio_main(asyncio_loop, asyncio_queue: asyncio.Queue, asyncio_shutdown_event: asyncio.Event):
    trio_token = trio.hazmat.current_trio_token()
    portal = AsyncioTrioPortal(asyncio_loop, trio_token)
    portal.run_sync_asyncio_from_trio(asyncio_queue.put, portal)
    await portal.run_asyncio_from_trio(asyncio_shutdown_event.wait)
```

So the idea is you start a thread running `trio.run(trio_main, ...)`, passing in the asyncio loop, and a queue and an event (using the asyncio versions of these because during the bootstrapping phase, asyncio is all we have!). Then in the asyncio thread you do `portal = await queue.get()` to get the portal, and then do whatever stuff you're going to do, and eventually, when you're ready to shut things down, you call `shutdown_event.set()`, and this wakes up `trio_main` and causes it to exit.

As soon as it exits, trio will automatically cancel all "system tasks", which includes the tasks we're using to run stuff via `portal.run{,_sync}_trio_from_asyncio`. So you do actually have a way to get them to shut down, once you jump through all the hoops to make it work at all :-). And the portal version has the potential advantage that the trio thread can be doing arbitrary work, without needing a task sitting around waiting for requests to arrive. Maybe that's not so useful in practice though?

Well, trio-asyncio is definitely cleaner if it works :-)
