### ISSUE TITLE
raven doesn't like LOCALS_KEY_KI_PROTECTION_ENABLED

### ISSUE THREAD

**Issue by lilydjwg** [python-trio/trio#469]
```py
import trio

async def main():
  from raven import Client
  client = Client(SENTRY_DSN)
  raise Exception

if __name__ == '__main__':
  trio.run(main)
```

The cause is:

```pybt
Error in sys.excepthook:
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/raven/utils/json.py", line 48, in dumps
    return json.dumps(value, cls=BetterJSONEncoder, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
```

It's because `trio._core._ki.LOCALS_KEY_KI_PROTECTION_ENABLED` is used as a key and raven collects it.

**Comment by njsmith** [comment]
Whoops, I guess I [won my bet](https://github.com/python-trio/trio/blob/aee2676fd5096daf2849db9756242a30e0aa1f30/trio/_core/_ki.py#L81-L83).

I'm not sure if this should be considered a bug in trio or in raven – we can work around it in trio by using a string key, but raven should perhaps be robust against this anyway :-).

You're going to run into some other issues with raven too, I think:

* Make sure to `import trio` before you `import raven`, because it looks like they both mess with `sys.excepthook`. If you `import raven` first, then it'll take over `sys.excepthook`, and then trio will notice that someone has taken it over and skip installing its hook, which means you won't get good tracebacks for `MultiError`s. If you `import trio` first, then raven will notice this and delegate to trio's hook after running its own, so that works better. (Unfortunately trio can't do the same thing, because it wants to *replace* the usual hook, while raven wants to *augment* the usual hook.)

* If raven is trying to capture frame information from unhandled exceptions, then it's not going to return very useful results for `MultiError` exceptions, because it won't know to peek inside and find the inner exception traceback frames.

It looks like raven has some [precedent for shipping integration code for specific libraries](https://docs.sentry.io/clients/python/integrations/), but I haven't looked any closer to see if its extension points are powerful enough to fix these issues...

I guess as a first step I'll file a bug on raven and see what they think.

**Comment by njsmith** [comment]
Raven issue: https://github.com/getsentry/raven-python/issues/1210

**Comment by mwchase** [comment]
It's sort of a different context, but pytest handles avoiding clashes by using string values that would be syntax errors: https://github.com/pytest-dev/pytest/blob/506c9c91c0127e66944c4e357f43fa2a46916fa7/_pytest/assertion/rewrite.py#L647

With that kind of approach, it's back to being a string value, but now the only thing that can clash is other generated names.

**Comment by miracle2k** [comment]
Is there a good reason to stick with the class, and not to use a different approach, such as the one @mwchase mentioned? This would solve not only the sentry issue, but also avoid potential trouble in the future with other tools.

**Comment by kyrias** [comment]
What about adding a string local with spaces?  Does raven complain about that?

**Comment by miracle2k** [comment]
I've been running a patched version with a @-prefixed string for a while now, it seems to work! https://github.com/miracle2k/trio/commit/22d9a4d572fbcace214979b0fcc3a7db83833bc0

**Comment by njsmith** [comment]
Yeah, we should probably go ahead and work around this. Raven will still have issues with `excepthook` and `MultiError`, but we can at least stop the crashes. And hopefully in 3.8 we can move `MultiError` into the stdlib and that should fix the other issues.

@miracle2k want to submit that patch as a PR?

**Comment by njsmith** [comment]
(ideally with a comment linking to issue, and a string that also includes the word "trio" for some rudimentary namespacing and as a clue for folks who stumble across it in their debugger )

**Comment by miracle2k** [comment]
PR in #599.
