### ISSUE TITLE
Upgrade pip on MacOS builder

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#487]
It looks like we still have pip 9.0.1 on our MacOS environments, which is causing tests to fail:
https://ci.cryptography.io/blue/organizations/jenkins/python-trio%2Ftrio/detail/PR-486/1/

I guess @reaperhulk is busy, but I think we could add a command like

`curl https://bootstrap.pypa.io/get-pip.py | python`

to `ci/travis.sh` before the first call to `pip`.

**Comment by jab** [comment]
Just submitted #488 with the changes you proposed and looks like it fixes this. Thanks for the pointers!

<details>
<summary>In case you have time...</summary>
<hr>
Curious how on earth you were able to tell that was the problem from that build output!
<br>
<br>
If pip 9.0.1 were the version, wouldn't `pip install -U pip setuptools wheel` have output something like

```
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
```
rather than "Requirement already up-to-date: pip...", which is what you get when the latest version (currently 9.0.3) is already installed?

And why would pip 9.0.1 be the reason that the wheel install failed? When I try to reproduce this error on my own Sierra machine, it doesn't reproduce:
```
$ /usr/local/var/pyenv/versions/3.5.5/bin/python3.5 -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip --version
pip 9.0.1 from /private/tmp/.venv/lib/python3.5/site-packages (python 3.5)
(.venv) $ pip install -U pip setuptools wheel
Collecting pip
  Using cached pip-9.0.3-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.31.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed pip-9.0.3 setuptools-39.0.1 wheel-0.31.0
```

![screen shot 2018-04-02 at 20 19 45](https://user-images.githubusercontent.com/64992/38198039-5e87533c-36b5-11e8-98e3-5f53c859722e.png)

One difference is that I used a pyenv-installed python3.5 that I had handy, rather than a /Library/Frameworks/...-installed version.

Perhaps that's why I don't reproduce the wheel install failure. But I'm not even reproducing the "Requirement already up-to-date: pip" output, so this really has me pretty mystified.

In any case, glad to see this fixed!
)))
</details>

**Comment by reaperhulk** [comment]
PyPI is going TLS 1.2 only very soon and is currently doing periodic brownouts where they disable 1.0 and 1.1 support to shake out clients that can't support that. pip < 9.0.2 on macOS doesn't support TLS 1.2 when run against Pythons that are linked against older versions of OpenSSL (this includes system Python on macOS < 10.13 as well as some python.org Pythons). urllib3 in pip 9.0.2+ has a securetransport shim written using ctypes specifically to work around this issue.

When pip is unable to connect because of this the error shown looks like what you see in that jenkins output.

**Comment by jab** [comment]
Wow, lots of different things ~interacting~ conspiring to cause this. Thanks for taking the time to explain.

My pyenv-installed python3.5 is linked against latest homebrew OpenSSL (1.0.2o  27 Mar 2018), so definitely different enough from what's running on Jenkins to thwart my attempted repro.

But it's still totally non-obvious why using TLS < 1.2 would cause pip 9.0.1 to report that the latest version of pip is already installed when trying to hit PyPI during a 1.0 and 1.1 brownout, rather than some kind of connection failure.

In any case, if I'd known that I'd have tried to add some more debugging output and/or asserts to this PR to give more visibility into all the hidden interactions that could be going on. At least I thought to include the comment linking to this PR...
