### ISSUE TITLE
SSLListener class doc incomplete

### ISSUE THREAD

**Issue by hjbyt** [python-trio/trio#540]
screenshot:
![screenshot](https://user-images.githubusercontent.com/5450806/40378331-e9b163ae-5dfb-11e8-935e-1d6f15dcecec.png)
It's understandable from context, but it seems the sentence is unfinished (allows me to wrap what?).
Maybe it's intended to be read as "allows you to wrap ... The listener whose incoming connections..." ? if so, a colon would make it clearer.

**Comment by njsmith** [comment]
Oh yeah, I got distracted half-way through the sentence and didn't notice. Nice catch :-). Should be something like "`SSLListener` wraps around another `Listener`, and converts all incoming connections to encrypted connections by wrapping them in an `SSLStream`."

I'm going to leave this open as a "good first issue", because it's simple enough but still a good opportunity to practice going through our [contribution process](https://trio.readthedocs.io/en/latest/contributing.html#preparing-pull-requests) on a real issue.
