### ISSUE TITLE
trio.CapacityLimiter(math.inf)

### ISSUE THREAD

**Issue by acarl005** [python-trio/trio#618]
Hello. Awesome concurrency library! I almost gave up on trying to use concurrency in Python. But Trio inspired me to stick with it.

I'm writing a library on top of Trio. I was hoping for an easy way to essentially "opt-out" of a capacity limit with a simple function argument. I tried something like this

```
limit = trio.CapacityLimiter(math.inf)
```

But this fails with the following error `TypeError: total_tokens must be an int`. It seems like it should be possible maybe. What do you think?

**Comment by njsmith** [comment]
> Awesome concurrency library! I almost gave up on trying to use concurrency in Python. But Trio inspired me to stick with it.

Thanks!

> I was hoping for an easy way to essentially "opt-out" of a capacity limit with a simple function argument.

Can you share more about what your use case is? I know there are valid ones, but the last time this came up (https://github.com/python-trio/trio/pull/587) I got stuck because I couldn't figure out how to explain them in the docs. (Though, that PR did things in a less elegant way that required more explanation; if you read the comments you'll see we ended up thinking that `CapacityLimiter(math.inf)` might be better too :-).)

In any case, I agree this would be a good thing to support. Any interest in putting together a PR? The `CapacityLimiter` code itself all works fine already with `capacity = inf`, so the actual change would be pretty simple: just change the argument checking to require the value be int-or-math.inf. But it'd be nice to also have a test and a release note – [see our contributing docs for details](https://trio.readthedocs.io/en/latest/contributing.html#preparing-pull-requests), or feel free to ask in [chat](https://gitter.im/python-trio/general). (And if you want to get a little fancier, there's [some code in trio/_wait_for_object.py](https://github.com/python-trio/trio/blob/7f0dd7de97722ffeb9cff8dc5fb66dd9b773fbf2/trio/_wait_for_object.py#L9-L14) that could be replaced by `CapacityLimiter(inf)`.)

**Comment by DjaPy** [comment]
Hi! Is it closed? I am a beginner, I want to understand how I can help

**Comment by njsmith** [comment]
@DjaPy Hello! You're right, this actually was fixed and the issue should have been closed, but sometimes these things get missed.... so, pointing that out is already a valuable contribution. You're off to a great start :-).

Unfortunately we're a bit short of "good first issues" right now, but there is this issue if you want to take a look: #251. It's a bit more complicated than `CapacityLimiter(inf)`, but there are some detailed notes in the issue that might help? Definitely ask if you have any questions, low-level socket APIs can be confusing.

Otherwise, well... it depends on what you're interested in :-). I definitely recommend joining [our gitter channel](https://gitter.im/python-trio/general) – that's where a lot of day-to-day discussion happens. There's a reply I wrote [here](https://github.com/python-trio/trio/issues/729#issuecomment-431744361) to someone who asked about helping with documentation. If you can say some more about what your background is and what you're interested in, either here or in the gitter, then we can probably come up with some suggestions :-).
