### ISSUE TITLE
trio.Cancelled missing readable str()

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#674]
Trying to print a trio.Cancelled exception e.g. with `f'{exc}'` yields an empty string.  I usually resort to `type(exc)` when I need to see what's going on.

**Comment by njsmith** [comment]
Yeah, this is an annoying general quirk in Python, that for exceptions, `__str__` just returns the bare exception message... which is almost never what you want. Instead you usually want `__repr__`, e.g., by doing `f"{exc!r}"`.

This is a bit worse for `Cancelled` than other exceptions. Most exceptions IME are merely vague and confusing when printed without the type for context; `Cancelled` OTOH has no message string associated with it at all.

Options:

We could do nothing at all, and tell people to use `__repr__`, since that's the general rule for exceptions anyway.

We could give `Cancelled` exceptions some boilerplate message like `"cancelled"`, so `f"{exc}"` would be `"cancelled"`, and tracebacks would look like:

```python
trio.Cancelled: cancelled
```

We could define a custom `__str__` (maybe just `__str__ = __repr__`), so that you get something useful out of `f"{exc}"` without adding redundancy to tracebacks.

I don't have a strong opinion here; all three options seem reasonable enough.

**Comment by belm0** [comment]
Thank you for explaining.

Custom `__str__` approach sounds good.  I would not want add "trio.Cancelled: cancelled" noise to tracebacks.
