### ISSUE TITLE
trio open_readfile failed, but aiofiles works

### ISSUE THREAD

**Issue by Alphapage** [python-trio/trio#675]
Hello,

I try to read a file on Windows like this:

```
async def read_file(path: str)->str:
    # async with aiofiles.open(path, mode='r') as file:
    #     return await file.read()

    # async with await trio.open_file(path,mode='r') as file:
    #     breakpoint()
    #     return await file.read()

    async with await trio.Path(path).open() as file:
    breakpoint()
    return await file.read()
```

With trio, breakpoint is never reached in both cases and I get an error: `must be called from async context
`

As it is working with aiofiles, I think I am in an async context.

Thank you in advance for your help.

Update: same error for mkdir

**Comment by njsmith** [comment]
Are you trying to use Trio from inside an asyncio program? Are you using `trio.run`? When it says "async context" it really means "Trio context", i.e. inside `trio.run`...

**Comment by Alphapage** [comment]
Yes, I am using asyncio.
I don't know about Trio context because I can't find a complete example of how to read a file using Trio. Sorry.

**Comment by Alphapage** [comment]
Finally, I found trio-asyncio, but I MUST replace asyncio.run with trio.run.
It is impossible to build a library using trio because of this limitation: I don't want to change the main asyncio loop.
aiofiles doesn't have this requirement to work. Are you planning to remove this limitation ?

**Comment by njsmith** [comment]
So in general, Trio and asyncio are different systems; you pick one or the other :-). (There's also [trio-asyncio](https://trio-asyncio.readthedocs.io/) if you need to use asyncio libraries from inside a trio program, but that's a more advanced use case.) If you want to get started with Trio, [here's the tutorial](https://trio.readthedocs.io/en/latest/tutorial.html), or here's a simple example of a program that reads a file using Trio:

```python
import trio

async def main():
    async with await trio.open_file("my-file.txt", mode="r") as file:
        data = await file.read()
    print(f"File has {len(data)} characters in it")

trio.run(main)
```

Notice that we use `trio.run` instead of `asyncio.run` or anything involving an asyncio loop object. This has to do with the "async sandwich" described in the tutorial I linked above...

**Comment by Alphapage** [comment]
Cross writing comment. Sorry.
So, will it be possible to remove `trio.run `and use `asyncio.run` soon or never ?

**Comment by smurfix** [comment]
Probably never. They are fundamentally different.

**Comment by Alphapage** [comment]
Thank you very much for your help.

**Comment by njsmith** [comment]
Whoops, cross-posted.

>  It is impossible to build a library using trio because of this limitation: I don't want to change the main asyncio loop.

That's true, if your requirement is that you use the asyncio loop, then you can't use trio, just like if your requirement is to use urllib then you can't use requests, or if your requirement is to use Java then you can't use Python :-). We don't plan to change this, because trio is based on fundamentally [different ideas](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/) than asyncio; we think this makes it simpler, easier to use, and more powerful. But if you want to use asyncio, that's cool too; it just means you're using asyncio, not trio.
