### ISSUE TITLE
pylint errors 

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#722]
unexpected pylint errors when my code is run against 0.8.0:
```
foo.py:252:8: E1101: Module 'trio.hazmat' has no 'add_instrument' member (no-member)
bar.py:155:15: E1101: Module 'trio' has no 'BrokenStreamError' member (no-member)
```
`add_instrument` should definitely be there
regarding `BrokenStreamError` I don't expect deprecated functions to be hidden from lint

**Comment by njsmith** [comment]
For `BrokenStreamError`, this is a side-effect of how it's defined: it's not actually in `trio.__dict__`, but instead is generated on the fly by the `trio` module's `__getattr__` method. Unfortunately, it's kind of hard to avoid this, because we actually need to generate the warning at attribute lookup time, or else code like `except trio.BrokenStreamError:` wouldn't generate a warning. We *could* redundantly create a variable and also add a hook to `__getattr__`, but I'm not sure it's worth the extra effort given that it's deprecated. So pylint is actually correct you shouldn't use it, even if it's wrong about why :-).

I have no idea what's going on with `add_instrument`.... it's definitely listed in `trio.hazmat.__all__`. Some strange pylint/astroid thing I guess? Would need to debug that, though hopefully we're going to redo the hazmat export machinery soon anyway...

**Comment by belm0** [comment]
The reason for the error on the hazmat module is already covered here:  https://github.com/PyCQA/pylint/issues/2382#issuecomment-411647553

pylint doesn't look at `__all__` and doesn't infer games with`globals()`
