### ISSUE TITLE
Use README for making a PyPI long_description.

### ISSUE THREAD

**Issue by RatanShreshtha** [python-trio/trio#729]
README files can be used to set the project’s description on PyPI. And we can also use it for trio as well this way we will not have to update the information at two places i.e README and setup.py.
Right now we are setting the long description using a multiline string.

[Making a PyPI-friendly README](https://packaging.python.org/guides/making-a-pypi-friendly-readme/)

**Comment by RatanShreshtha** [comment]
@njsmith I would like to get your opinion on that.

**Comment by njsmith** [comment]
Hi Ratan,

I guess I don't have a strong feeling about it either way? The target audiences are slightly different... but not enough for it to matter much. The duplication creates extra work in theory... but in practice we haven't touched either in more than a year, so it's not actually causing any problems. It just doesn't seem like a high priority to me either way.

Are you looking for ways you can help contribute? If you want to say a bit more about where you're coming from and what you're interested in, we could definitely suggest some ideas.

**Comment by RatanShreshtha** [comment]
Hi @njsmith 
I am looking for ways to contribute to trio, I like the project. I am from India and I am interested in understanding how the async work.

For me, the documentation seems like a good way to contribute as I am not that good technically.

**Comment by RatanShreshtha** [comment]
Hi @njsmith 

Waiting for your ideas and guidance for contribution.

**Comment by njsmith** [comment]
Hi Ratan, sorry for the slow response! It'd be great to have you, I've just been super scattered this week.

Can you say a bit more about what your technical background is, and what kind of things you'd like to do? Documentation is definitely a great place to contribute, but if what you really want to do is work on code but are just settling for documentation because you don't feel like you have enough experience to work on code, then it might make more sense to practice coding and get better :-).

But, if you want a suggestion for a documentation project: I think we should have a page in the docs with a list of "recommended packages", with brief descriptions of pytest-trio, asks, etc. But this needs someone to assemble the list, and maintain it. I'm thinking of something like [awesome-python](https://github.com/vinta/awesome-python), but just for Trio. (So much smaller, at least for now :-).) Would that be something you're interested in?

Other ideas:

* Keep reading the gitter, to see what people are working on and having trouble with, and see if it gives you any ideas.
* Find some simple projects to experiment with learning Trio yourself. Make detailed notes on what parts you find confusing! Or teach a friend, and make notes on where they get stuck. Post the notes as an issue. This is *super* useful.
* Pick a simple project, implement it using both asyncio and Trio, then write up a blog post talking about your experience.
* Work through the issue tracker, reading through say 3 issues a day. At the least you'll learn things; and you may get ideas for useful contributions, or find an old issue that's been fixed and can be closed, or even just notice that two issues are related and so it's helpful to post a comment linking between them.
* Ask for suggestions on gitter, see if anyone responds :-).

**Comment by njsmith** [comment]
Hi Ratan, sorry for the slow response! It'd be great to have you, I've just been super scattered this week.

Can you say a bit more about what your technical background is, and what kind of things you'd like to do? Documentation is definitely a great place to contribute, but if what you really want to do is work on code but are just settling for documentation because you don't feel like you have enough experience to work on code, then it might make more sense to practice coding and get better :-).

But, if you want a suggestion for a documentation project: I think we should have a page in the docs with a list of "recommended packages", with brief descriptions of pytest-trio, asks, etc. But this needs someone to assemble the list, and maintain it. I'm thinking of something like [awesome-python](https://github.com/vinta/awesome-python), but just for Trio. (So much smaller, at least for now :-).) Would that be something you're interested in?

Other ideas:

* Keep reading the gitter, to see what people are working on and having trouble with, and see if it gives you any ideas.
* Find some simple projects to experiment with learning Trio yourself. Make detailed notes on what parts you find confusing! Or teach a friend, and make notes on where they get stuck. Post the notes as an issue. This is *super* useful.
* Pick a simple project, implement it using both asyncio and Trio, then write up a blog post talking about your experience.
* Work through the issue tracker, reading through say 3 issues a day. At the least you'll learn things; and you may get ideas for useful contributions, or find an old issue that's been fixed and can be closed, or even just notice that two issues are related and so it's helpful to post a comment linking between them.
* Ask for suggestions on gitter, see if anyone responds :-).

**Comment by njsmith** [comment]
Hi Ratan, sorry for the slow response! It'd be great to have you, I've just been super scattered this week.

Can you say a bit more about what your technical background is, and what kind of things you'd like to do? Documentation is definitely a great place to contribute, but if what you really want to do is work on code but are just settling for documentation because you don't feel like you have enough experience to work on code, then it might make more sense to practice coding and get better :-).

But, if you want a suggestion for a documentation project: I think we should have a page in the docs with a list of "recommended packages", with brief descriptions of pytest-trio, asks, etc. But this needs someone to assemble the list, and maintain it. I'm thinking of something like [awesome-python](https://github.com/vinta/awesome-python), but just for Trio. (So much smaller, at least for now :-).) Would that be something you're interested in?

Other ideas:

* Keep reading the gitter, to see what people are working on and having trouble with, and see if it gives you any ideas.
* Find some simple projects to experiment with learning Trio yourself. Make detailed notes on what parts you find confusing! Or teach a friend, and make notes on where they get stuck. Post the notes as an issue. This is *super* useful.
* Pick a simple project, implement it using both asyncio and Trio, then write up a blog post talking about your experience.
* Work through the issue tracker, reading through say 3 issues a day. At the least you'll learn things; and you may get ideas for useful contributions, or find an old issue that's been fixed and can be closed, or even just notice that two issues are related and so it's helpful to post a comment linking between them.
* Ask for suggestions on gitter, see if anyone responds :-).

**Comment by RatanShreshtha** [comment]
Thanks, @njsmith I am working with @pquentin to port urllib3 to async/await. 
I will also keep in mind your suggestions.

**Comment by Zac-HD** [comment]
Closing this as inactive, and because I think the status quo is fine.
