### ISSUE TITLE
Describing 'start_soon' as 'synchronous' is confusing to newcomers from other frameworks

### ISSUE THREAD

**Issue by AdrienPensart** [python-trio/trio#779]
https://trio.readthedocs.io/en/latest/reference-core.html#trio.The%20nursery%20interface

"Note that this is a synchronous function: it sets up the new task, but then returns immediately, before it has a chance to run."

Should be : 

"Note that this is a**n a**synchronous function: it sets up the new task, but then returns immediately, before it has a chance to run."

**Comment by njsmith** [comment]
Oh, that terminology is kind of confusing, isn't it.

The text is correct as is, **if** you know that when we say "asynchronous function", we mean "a function defined with `async def` and called with `await`", and when we say "synchronous function" we mean a regular function defined with regular `def` and called without `await`.

I guess you're coming from a system where "asynchronous" means "schedules something to be run later, without waiting for it". But we systematically avoid ever defining functions like that, for the reasons [described here](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/). For us, asynchronous functions and synchronous functions both perform some work and wait for it to finish. The very rare exceptions like `start_soon` usually have `start` in the name to emphasize that they do this strange thing.

The reason these two very different concepts both use the word "async" is because the functions that Trio makes async-in-Trio's-sense are the same ones that other frameworks would make async-in-their-sense. Also, because the word "async" is baked into Python's syntax, so there isn't really any way to avoid it.

But not everyone reading the Trio docs is going to know all that, and that sentence does leave a lot of potential for confusion.

Maybe something like:

"""
Note that this is **not** an `async` function, and you **don't** use `await` when calling it. It sets up the new task, but then returns immediately, before it has a chance to run. The new task won’t actually get a chance to do anything until some later point when you execute a checkpoint and the scheduler decides to run it. If you want to run a function and immediately wait for its result, then you don't need a nursery; just use `await async_fn(*args)`. If you want to wait for the task to initialize itself before continuing, see `start()`.
"""

What do you think?

**Comment by AdrienPensart** [comment]
Perfect, I think going the negative sentence way is better as it breaks confusion :+1:

**Comment by pquentin** [comment]
@AdrienPensart Great! Would you like to open a PR to fix the docs with the proposed change?

**Comment by AdrienPensart** [comment]
Here we are:

#780
