### ISSUE TITLE
trio.run_process

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#822]
So #791 added the core support for subprocesses, but at the last minute we had doubts about copying `subprocess.run` and decided to split out the high level convenience API into a separate PR: https://github.com/python-trio/trio/pull/791#issuecomment-449325056

Some issues to consider (it's worth reading the whole discussion linked above):

* probably make `check=True` as the default. (Might be worth considering making the name more descriptive, so people would write `allow_failure=True`?)
* Passing `stdout=PIPE` to mean "capture the output" is pretty confusing (basically just dumping an implementation detail into the public API). Maybe `capture_stdout=`/`capture_stderr=` as boolean kwargs? Should we have `capture=` as a shorthand for setting both at once?
* If we're changing the default for `check`, we should change the name, because that's just enough of a change for people to trip over. `trio.run_process` is a good name.
* Should we do anything about the weird mess around `shell=True` and string-versus-list commands?

**Comment by njsmith** [comment]
Also my intuition is still yelling at me that having `timeout`/`deadline` on `run_process` is something we'll look back on as a bit of excessive enthusiasm overriding simplicity and consistency, so I guess I should mention that here, if only as something we might want to look back at in 6-12 months before all our APIs lock solid.

**Comment by njsmith** [comment]
It looks like asyncio chose to split up `shell=True` and `shell=False` into two separate functions, and doesn't give any way to specify a raw string on Windows: https://docs.python.org/3/library/asyncio-subprocess.html

**Comment by ncoghlan** [comment]
Regarding the name of `check`, the rationale for calling it that was to retain consistency between the parameter name and the method name on the returned object (i.e. `result.check_returncode()`), as well as the earlier `check_call()` and `check_output()` APIs.

You *could* rename it so folks had to write `skip_check=True` instead of `check=False`, but at that point you've not only changed the defaults relative to `subprocess`, you've also changed the calling signature, and that strikes me as a difference that doesn't provide enough benefit to be worth the hassle created by introducing the inconsistency.

The reason I prefer `capture_output` to `capture_stdout` and `capture_stderr` is that once you're to the level of sophistication of caring about routing them differently, it isn't much of burden to drop down to the level of the existing `stdout` and `stderr` options, where you can choose between:
- routing both of them to separate pipes (same as `capture_output=True`)
- routing stderr into stdout (regardless of whether stdout is a pipe or not)
- routing one or both of them into devnull (so the output gets discarded without needing to care about keeping an interprocess pipe from filling up)

(Don't worry about inadvertently capturing the terminal for things like `sudo` or `ssh` password prompts - they know how to go hunting for the real attached terminal, and ignore any intervening pipe redirects)
