### ISSUE TITLE
Delay deciding which cancel scope a Cancelled exception belongs to

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#860]
Right now, whenever we create a `Cancelled` exception, we immediately tag it with the cancel scope that's going to catch it.

There's another option that's briefly mentioned in #606: we could wait until `CancelScope.__exit__` to decide whether a given `Cancelled` exception "belongs" to this scope. The check would be "on the current task's stack, am I the outermost unshielded scope that's in the cancelled state?"

This can behave differently from what we have now in cases where there are multiple cancelled `CancelScope`s on the stack.

I'm not entirely sure if this would actually help with #606, because of complications noted there (hello `KeyboardInterrupt`). But it would probably simplify the cancel scope code in general, in particular `_cancel_no_notify`, and the issues described in this comment: https://github.com/python-trio/trio/pull/835#issuecomment-455107324

**Comment by oremanj** [comment]
I just posted #900 which offers a less elegant, but also less invasive, solution to this problem. I prefer the solution in this issue on aesthetic grounds but I couldn't convince myself that it would be safe in the presence of a cancellation landscape that might be changing as the `Cancelled` exception propagates. Also, it makes the delivery of a cancellation be quadratic in the depth of the cancel stack, but probably that doesn't add up to much in practice?

**Comment by njsmith** [comment]
> couldn't convince myself that it would be safe in the presence of a cancellation landscape that might be changing as the `Cancelled` exception propagates

Good question, yeah.

Right now, at the moment when we inject the `Cancelled` exception, we look at a single consistent snapshot of the whole stack, determine where the outermost-unshielded-cancelled-scope is, and then lock that in as the destination of the exception.

In this proposal, each time the exception passes through a cancel scope, we look at a single consistent snapshot of the whole stack, and determine whether the current scope is the outermost-unshielded-cancelled-scope. (So the naive implementation is O(stack depth * number of scopes in the cancel-requested state), which is probably much better than O(stack depth * stack depth), and I think this could be optimized further.)

Now, if we discover that this *is* the outermost-unshielded-cancelled-scope, and catch the exception, then that's definitely OK, because it was the right thing to do at the moment we did it, and then there's nothing afterwards that could go wrong.

The riskier case is when we decide *not* to catch the exception. We know that at the moment we made the decision, there was some outer scope that was a better candidate for catching it. But, what it won't actually be caught until later. Could something happen between now and then that would mess things up? In particular, the thing that would be bad is if we got into a state where there was a live `Cancelled` propagating, but there *was no* outer scope that was a candidate for catching it. So, could that outer scope somehow stop being a candidate between when we raise the exception and when the exception reaches it?

To be a candidate, a scope has to meet two criteria:

* It has to be in the cancel-requested state
* There can't be any other scope that's in the cancel-requested state and that falls between our candidate and the next outermost shield

Once a scope is in the cancel-requested state, it can never leave it. So if we identified a scope as being a candidate at time T1, then for all times T2 > T1 it is definitely still in the cancel-requested state. But what about the second criterion? It could certainly happen that our original candidate stops fulfilling that – while our `Cancelled` is propagating, an outer scope could enter the cancel-requested state, or a shield could be removed to reveal an outer scope that was already in the cancel-requested state. But, in all of these cases, it means that our candidate is *replaced by another, even-more-outer candidate*.

Therefore, if in a snapshot at time T1 we decide that our exception has an outer candidate, then we are guaranteed that it will eventually be caught at time T2, even if it's by a different scope than the one we originally thought.

Ah, and I see you've just posted osmething too! I will read it.

**Comment by njsmith** [comment]
OK looks like we made pretty much the same argument :-)

**Comment by oremanj** [comment]
Put another way, if a cancel scope does interpret a Cancelled exception as being "for us", we can assume that determination is correct (as a matter of definition - the mapping from cancel stacks to "which scope is cancelled here right now" defines the cancellation semantics, we're just following it). So the only real correctness concern is that everyone could conclude "not mine!" and let a `Cancelled` exception fly out of the entire program. But for a cancelled scope to say "not mine!", it has to find some specific other further-out cancelled scope that it believes will say "mine!", based on the current state of the cancel stack. Since scopes never become uncancelled, at minimum the outermost cancelled scope will be forced to conclude "mine!". So as long as we never throw `Cancelled` into a task without any cancelled scopes on its cancel stack, we'll be OK.

**Comment by oremanj** [comment]
Great, I'm sufficiently convinced now and will close #900 and work on this instead. :-)

**Comment by oremanj** [comment]
Running the testsuite with the new behavior exposed a corner case I wasn't expecting, though I don't think it's actually harmful. If you have multiple tasks that are sleeping until the same time using `trio.sleep()`, and when one of them wakes up it cancels the others, the others will raise `Cancelled` out of that same call to `trio.sleep()` -- because `sleep()` is implemented using cancellation, and when the `Cancelled` reaches it, it sees there's a further-out cancelled scope that it should prefer instead.

**Comment by njsmith** [comment]
Oh yeah, this will definitely change behavior in some edge cases. And some of our low-level tests are very reliant on edge cases, or even checking for them explicitly, so they'll need a bit of tweaking for sure...
