### ISSUE TITLE
Should we make the generated code of #805 part of the build process?

### ISSUE THREAD

**Issue by jmfrank63** [python-trio/trio#935]
Discussion:
Imho there is no point in having the generated code in source control. As we have a code generator, the build process should just create the code on the fly.
Since a developer cannot change the code anyway it should not be part of the source.
Additionally the naming `_generated_*` could be adapted to something more descriptive that does not confuse users when the source file name appears in code completion.

**Comment by njsmith** [comment]
Oh whoops, apparently I missed this back in February.

Yeah, both ways can work, and there are advantages and disadvantages to both approaches.

The main advantage of generating the code on the fly is that it automatically stays up to date – so we don't need to check that it's up to date in CI, and developers never need to manually re-generate the code.

The main disadvantage is that you *have* to run the build process before you can run tests, or tools like mypy. (Not that we use mypy now, but presumably we will in the future.)

When I'm working on Trio, I find it very convenient to be able to run the tests directly out of the source tree without having to faff around with rebuilding or editable installs or anything like that. Having to do builds would add significant friction to my workflow. OTOH, this particular generated code changes very rarely. (I think we've only had to re-run the generator script once since it was merged last month, and I've run the tests way more times than that :-).) So for now, for this particular generated code in this particular project, I think checking it in is the way to go. But if the situation changes we can always revisit that.

**Comment by jmfrank63** [comment]
Hi Nathaniel,

thanks for the feedback, as always very helpful and gives great insight.

Your contrast makes perfectly sense.

Cheers Johannes
