### ISSUE TITLE
Make yapf part of the build process

### ISSUE THREAD

**Issue by jmfrank63** [python-trio/trio#936]
Discussion:
Instead of checking if the source code matches in `check.sh` directly format the code, so developers do not have to care about formatting anymore.

Especially since yapf seems to produce different results depending on OS, formatting the code during the build process would give consistent results for everybody and remove the need for manually running yapf.

**Comment by njsmith** [comment]
Unfortunately there are a bunch of challenges with having the CI push changes back to github. It involves secret management, and then submitters have changes appearing on their PR that they have to merge with their local work, ... I don't know how to make it work practically

**Comment by jmfrank63** [comment]
Admitted, it is not nice, but Travis actually has a way of doing it:
https://docs.travis-ci.com/user/deployment/pages/
Yes, it requires a secret but that seems to be securely doable.

**Comment by pquentin** [comment]
Note that yapf is now automatically upgraded by dependabot. See https://github.com/python-trio/trio/pull/920 for an example. So that should remove most of the pain for PRs that don't need to rebase/merge from master.

In #805, you got confused because you merged from master, which upgraded the yapf version, but you forgot to upgrade your dependencies locally. That's a problem with long-running PRs. :/ If CI had pushed a formatting commit, then your next push would have failed unless you had thought about pulling from the remote branch first.

Does that make sense?

**Comment by jmfrank63** [comment]
Thanks, Quentin, you have always be a source of great knowledge and are so
helpful. I really appreciate your help. Hopefully I avoid the trap with
pipenv next time.
I am also thinking about checking Pipfiles in, pipenv is not so rare
anymore and who does not use them would not be hurt.

**Comment by pquentin** [comment]
@jmfrank63 See https://discuss.python.org/t/structured-exchangeable-lock-file-format-requirements-txt-2-0/876/4 where @njsmith explains why pipenv is not versatile enough for the trio usecase.

I'm sorry that the current situation is not ideal, but I don't think we can do much about it, so I'll close this issue for now. Feel free to reopen!
